// Starter AP English Literature free-response library.
//
// Q1 (poetry) and Q2 (prose) ship a provided text drawn from the public
// domain so it can live in the repo. Q3 (literary argument) ships no text —
// students supply a work of literary merit from memory — but includes
// suggested works to seed the "arsenal" a strong Q3 response draws on.

export const AP_ENGLISH_LIT_LIBRARY_ENTRIES = [
  {
    externalKey: 'ap-lit-poetry-frost-acquainted-with-the-night',
    frqType: 'poetry',
    title: 'Acquainted with the Night — Poetry Analysis',
    prompt:
      "Read the following poem carefully. Then, in a well-written essay, analyze how Frost uses literary techniques to convey the speaker's complex relationship with solitude and the city at night.",
    focusSkill: 'speaker-attitude',
    difficulty: 'exam-ready',
    skillEmphasis: 'evidence-commentary',
    defaultTimeMode: 'untimed',
    defaultDurationMinutes: 40,
    suggestedWorks: null,
    provenanceUrl: 'https://www.poetryfoundation.org/poems/47548/acquainted-with-the-night',
    sources: [
      {
        externalKey: 'ap-lit-poetry-frost-acquainted-with-the-night-poem',
        position: 1,
        title: 'Acquainted with the Night',
        attribution: 'Robert Frost, 1928 (public domain)',
        body: [
          'I have been one acquainted with the night.',
          'I have walked out in rain — and back in rain.',
          'I have outwalked the furthest city light.',
          '',
          'I have looked down the saddest city lane.',
          'I have passed by the watchman on his beat',
          'And dropped my eyes, unwilling to explain.',
          '',
          'I have stood still and stopped the sound of feet',
          'When far away an interrupted cry',
          'Came over houses from another street,',
          '',
          'But not to call me back or say good-bye;',
          'And further still at an unearthly height,',
          'One luminary clock against the sky',
          '',
          'Proclaimed the time was neither wrong nor right.',
          'I have been one acquainted with the night.',
        ].join('\n'),
        caption: 'A terza rima sonnet on urban isolation.',
        mediaType: 'text',
        imageUrl: null,
        imageAlt: null,
        provenanceUrl:
          'https://www.poetryfoundation.org/poems/47548/acquainted-with-the-night',
      },
    ],
  },
  {
    externalKey: 'ap-lit-prose-austen-pride-and-prejudice-opening',
    frqType: 'prose',
    title: 'Pride and Prejudice Opening — Prose Fiction Analysis',
    prompt:
      "Read the following passage carefully. Then, in a well-written essay, analyze how Austen uses techniques such as irony, dialogue, and narrative voice to characterize the Bennet marriage and the world of the novel.",
    focusSkill: 'characterization',
    difficulty: 'exam-ready',
    skillEmphasis: 'evidence-commentary',
    defaultTimeMode: 'untimed',
    defaultDurationMinutes: 40,
    suggestedWorks: null,
    provenanceUrl: 'https://www.gutenberg.org/ebooks/1342',
    sources: [
      {
        externalKey: 'ap-lit-prose-austen-pride-and-prejudice-opening-passage',
        position: 1,
        title: 'From Pride and Prejudice, Chapter 1',
        attribution: 'Jane Austen, 1813 (public domain)',
        body: [
          'It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.',
          '',
          'However little known the feelings or views of such a man may be on his first entering a neighbourhood, this truth is so well fixed in the minds of the surrounding families, that he is considered the rightful property of some one or other of their daughters.',
          '',
          '"My dear Mr. Bennet," said his lady to him one day, "have you heard that Netherfield Park is let at last?"',
          '',
          'Mr. Bennet replied that he had not.',
          '',
          '"But it is," returned she; "for Mrs. Long has just been here, and she told me all about it."',
          '',
          'Mr. Bennet made no answer.',
          '',
          '"Do you not want to know who has taken it?" cried his wife impatiently.',
          '',
          '"You want to tell me, and I have no objection to hearing it."',
          '',
          'This was invitation enough.',
        ].join('\n'),
        caption: 'The novel\'s famous opening and the first Bennet exchange.',
        mediaType: 'text',
        imageUrl: null,
        imageAlt: null,
        provenanceUrl: 'https://www.gutenberg.org/ebooks/1342',
      },
    ],
  },
  {
    externalKey: 'ap-lit-argument-moral-ambiguity',
    frqType: 'literary_argument',
    title: 'Moral Ambiguity — Literary Argument',
    prompt:
      "Many works of literature feature a character whose moral ambiguity — being neither wholly good nor wholly evil — is central to the work. Select a novel or play of literary merit in which a character is morally ambiguous. Then, in a well-written essay, analyze how that moral ambiguity contributes to an interpretation of the work as a whole. Do not merely summarize the plot.",
    focusSkill: 'moral-ambiguity',
    difficulty: 'exam-ready',
    skillEmphasis: 'sophistication',
    defaultTimeMode: 'untimed',
    defaultDurationMinutes: 40,
    suggestedWorks: [
      'Crime and Punishment — Fyodor Dostoevsky',
      'Beloved — Toni Morrison',
      'Hamlet — William Shakespeare',
      'The Great Gatsby — F. Scott Fitzgerald',
      'Wuthering Heights — Emily Brontë',
    ].join('\n'),
    provenanceUrl: 'https://apcentral.collegeboard.org/courses/ap-english-literature-and-composition/exam',
    sources: [],
  },
  {
    externalKey: 'ap-lit-argument-significance-of-setting',
    frqType: 'literary_argument',
    title: 'The Significance of Setting — Literary Argument',
    prompt:
      "In many works of literature, a physical setting — a house, a city, a landscape — carries meaning beyond its literal presence. Select a novel or play of literary merit in which a setting is significant. Then, in a well-written essay, analyze how the setting contributes to an interpretation of the work as a whole. Do not merely summarize the plot.",
    focusSkill: 'setting-as-meaning',
    difficulty: 'intro',
    skillEmphasis: 'evidence-commentary',
    defaultTimeMode: 'untimed',
    defaultDurationMinutes: 40,
    suggestedWorks: [
      'Their Eyes Were Watching God — Zora Neale Hurston',
      'Jane Eyre — Charlotte Brontë',
      'The Grapes of Wrath — John Steinbeck',
      'A Streetcar Named Desire — Tennessee Williams',
    ].join('\n'),
    provenanceUrl: 'https://apcentral.collegeboard.org/courses/ap-english-literature-and-composition/exam',
    sources: [],
  },
] as const;
