// Starter AP English Literature free-response library.
//
// Q1 (poetry) and Q2 (prose) ship a provided text drawn from the public
// domain so it can live in the repo. Q3 (literary argument) ships no text —
// students supply a work of literary merit from memory — but includes
// suggested works to seed the "arsenal" a strong Q3 response draws on.

export const AP_ENGLISH_LIT_LIBRARY_ENTRIES = [
  {
    externalKey: 'ap-lit-poetry-frost-acquainted-with-the-night',
    frqType: 'poetry',
    title: 'Acquainted with the Night — Poetry Analysis',
    prompt:
      "Read the following poem carefully. Then, in a well-written essay, analyze how Frost uses literary techniques to convey the speaker's complex relationship with solitude and the city at night.",
    focusSkill: 'speaker-attitude',
    difficulty: 'exam-ready',
    skillEmphasis: 'evidence-commentary',
    defaultTimeMode: 'untimed',
    defaultDurationMinutes: 40,
    suggestedWorks: null,
    provenanceUrl: 'https://www.poetryfoundation.org/poems/47548/acquainted-with-the-night',
    sources: [
      {
        externalKey: 'ap-lit-poetry-frost-acquainted-with-the-night-poem',
        position: 1,
        title: 'Acquainted with the Night',
        attribution: 'Robert Frost, 1928 (public domain)',
        body: [
          'I have been one acquainted with the night.',
          'I have walked out in rain—and back in rain.',
          'I have outwalked the furthest city light.',
          '',
          'I have looked down the saddest city lane.',
          'I have passed by the watchman on his beat',
          'And dropped my eyes, unwilling to explain.',
          '',
          'I have stood still and stopped the sound of feet',
          'When far away an interrupted cry',
          'Came over houses from another street,',
          '',
          'But not to call me back or say good-bye;',
          'And further still at an unearthly height,',
          'One luminary clock against the sky',
          '',
          'Proclaimed the time was neither wrong nor right.',
          'I have been one acquainted with the night.',
        ].join('\n'),
        caption: 'A terza rima sonnet on urban isolation.',
        mediaType: 'text',
        imageUrl: null,
        imageAlt: null,
        provenanceUrl:
          'https://www.poetryfoundation.org/poems/47548/acquainted-with-the-night',
      },
    ],
  },
  {
    externalKey: 'ap-lit-prose-austen-pride-and-prejudice-opening',
    frqType: 'prose',
    title: 'Pride and Prejudice Opening — Prose Fiction Analysis',
    prompt:
      "Read the following passage carefully. Then, in a well-written essay, analyze how Austen uses techniques such as irony, dialogue, and narrative voice to characterize the Bennet marriage and the world of the novel.",
    focusSkill: 'characterization',
    difficulty: 'exam-ready',
    skillEmphasis: 'evidence-commentary',
    defaultTimeMode: 'untimed',
    defaultDurationMinutes: 40,
    suggestedWorks: null,
    provenanceUrl: 'https://www.gutenberg.org/ebooks/1342',
    sources: [
      {
        externalKey: 'ap-lit-prose-austen-pride-and-prejudice-opening-passage',
        position: 1,
        title: 'From Pride and Prejudice, Chapter 1',
        attribution: 'Jane Austen, 1813 (public domain)',
        body: [
          'It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.',
          '',
          'However little known the feelings or views of such a man may be on his first entering a neighbourhood, this truth is so well fixed in the minds of the surrounding families, that he is considered as the rightful property of some one or other of their daughters.',
          '',
          '"My dear Mr. Bennet," said his lady to him one day, "have you heard that Netherfield Park is let at last?"',
          '',
          'Mr. Bennet replied that he had not.',
          '',
          '"But it is," returned she; "for Mrs. Long has just been here, and she told me all about it."',
          '',
          'Mr. Bennet made no answer.',
          '',
          '"Do you not want to know who has taken it?" cried his wife impatiently.',
          '',
          '"You want to tell me, and I have no objection to hearing it."',
          '',
          'This was invitation enough.',
        ].join('\n'),
        caption: 'The novel\'s famous opening and the first Bennet exchange.',
        mediaType: 'text',
        imageUrl: null,
        imageAlt: null,
        provenanceUrl: 'https://www.gutenberg.org/ebooks/1342',
      },
    ],
  },
  {
    externalKey: 'ap-lit-argument-moral-ambiguity',
    frqType: 'literary_argument',
    title: 'Moral Ambiguity — Literary Argument',
    prompt:
      "Many works of literature feature a character whose moral ambiguity — being neither wholly good nor wholly evil — is central to the work. Select a novel or play of literary merit in which a character is morally ambiguous. Then, in a well-written essay, analyze how that moral ambiguity contributes to an interpretation of the work as a whole. Do not merely summarize the plot.",
    focusSkill: 'moral-ambiguity',
    difficulty: 'exam-ready',
    skillEmphasis: 'sophistication',
    defaultTimeMode: 'untimed',
    defaultDurationMinutes: 40,
    suggestedWorks: [
      'Crime and Punishment — Fyodor Dostoevsky',
      'Beloved — Toni Morrison',
      'Hamlet — William Shakespeare',
      'The Great Gatsby — F. Scott Fitzgerald',
      'Wuthering Heights — Emily Brontë',
    ].join('\n'),
    provenanceUrl: 'https://apcentral.collegeboard.org/courses/ap-english-literature-and-composition/exam',
    sources: [],
  },
  {
    externalKey: 'ap-lit-argument-significance-of-setting',
    frqType: 'literary_argument',
    title: 'The Significance of Setting — Literary Argument',
    prompt:
      "In many works of literature, a physical setting — a house, a city, a landscape — carries meaning beyond its literal presence. Select a novel or play of literary merit in which a setting is significant. Then, in a well-written essay, analyze how the setting contributes to an interpretation of the work as a whole. Do not merely summarize the plot.",
    focusSkill: 'setting-as-meaning',
    difficulty: 'intro',
    skillEmphasis: 'evidence-commentary',
    defaultTimeMode: 'untimed',
    defaultDurationMinutes: 40,
    suggestedWorks: [
      'Their Eyes Were Watching God — Zora Neale Hurston',
      'Jane Eyre — Charlotte Brontë',
      'The Grapes of Wrath — John Steinbeck',
      'A Streetcar Named Desire — Tennessee Williams',
    ].join('\n'),
    provenanceUrl: 'https://apcentral.collegeboard.org/courses/ap-english-literature-and-composition/exam',
    sources: [],
  },

  // --- Poetry analysis (Q1) — public-domain poems ---
  {
    externalKey: 'ap-lit-poetry-dickinson-hope',
    frqType: 'poetry',
    title: '"Hope" is the thing with feathers — Poetry Analysis',
    prompt:
      "Read the following poem carefully. Then, in a well-written essay, analyze how Dickinson uses figurative language and form to develop the speaker's complex understanding of hope.",
    focusSkill: 'figurative-language',
    difficulty: 'exam-ready',
    skillEmphasis: 'evidence-commentary',
    defaultTimeMode: 'untimed',
    defaultDurationMinutes: 40,
    suggestedWorks: null,
    provenanceUrl: 'https://www.poetryfoundation.org/poems/42889/hope-is-the-thing-with-feathers-314',
    sources: [
      {
        externalKey: 'ap-lit-poetry-dickinson-hope-poem',
        position: 1,
        title: '"Hope" is the thing with feathers',
        attribution: 'Emily Dickinson, c. 1861 (public domain)',
        body: [
          '"Hope" is the thing with feathers -',
          'That perches in the soul -',
          'And sings the tune without the words -',
          'And never stops - at all -',
          '',
          'And sweetest - in the Gale - is heard -',
          'And sore must be the storm -',
          'That could abash the little Bird',
          'That kept so many warm -',
          '',
          "I've heard it in the chillest land -",
          'And on the strangest Sea -',
          'Yet - never - in Extremity,',
          'It asked a crumb - of me.',
        ].join('\n'),
        caption: 'An extended metaphor for hope.',
        mediaType: 'text',
        imageUrl: null,
        imageAlt: null,
        provenanceUrl: 'https://www.poetryfoundation.org/poems/42889/hope-is-the-thing-with-feathers-314',
      },
    ],
  },
  {
    externalKey: 'ap-lit-poetry-frost-nothing-gold',
    frqType: 'poetry',
    title: '"Nothing Gold Can Stay" — Poetry Analysis',
    prompt:
      "Read the following poem carefully. Then, in a well-written essay, analyze how Frost uses form, sound, and allusion to convey the speaker's attitude toward change and loss.",
    focusSkill: 'form-and-structure',
    difficulty: 'intro',
    skillEmphasis: 'thesis',
    defaultTimeMode: 'untimed',
    defaultDurationMinutes: 40,
    suggestedWorks: null,
    provenanceUrl: 'https://www.poetryfoundation.org/poems/148652/nothing-gold-can-stay',
    sources: [
      {
        externalKey: 'ap-lit-poetry-frost-nothing-gold-poem',
        position: 1,
        title: 'Nothing Gold Can Stay',
        attribution: 'Robert Frost, 1923 (public domain)',
        body: [
          "Nature's first green is gold,",
          'Her hardest hue to hold.',
          "Her early leaf's a flower;",
          'But only so an hour.',
          'Then leaf subsides to leaf.',
          'So Eden sank to grief,',
          'So dawn goes down to day.',
          'Nothing gold can stay.',
        ].join('\n'),
        caption: 'An eight-line meditation on impermanence.',
        mediaType: 'text',
        imageUrl: null,
        imageAlt: null,
        provenanceUrl: 'https://www.poetryfoundation.org/poems/148652/nothing-gold-can-stay',
      },
    ],
  },
  {
    externalKey: 'ap-lit-poetry-shelley-ozymandias',
    frqType: 'poetry',
    title: '"Ozymandias" — Poetry Analysis',
    prompt:
      "Read the following poem carefully. Then, in a well-written essay, analyze how Shelley uses irony, imagery, and the framing of the speaker to develop a commentary on power and time.",
    focusSkill: 'irony-and-tone',
    difficulty: 'exam-ready',
    skillEmphasis: 'sophistication',
    defaultTimeMode: 'untimed',
    defaultDurationMinutes: 40,
    suggestedWorks: null,
    provenanceUrl: 'https://www.poetryfoundation.org/poems/46565/ozymandias',
    sources: [
      {
        externalKey: 'ap-lit-poetry-shelley-ozymandias-poem',
        position: 1,
        title: 'Ozymandias',
        attribution: 'Percy Bysshe Shelley, 1818 (public domain)',
        body: [
          'I met a traveller from an antique land,',
          'Who said—"Two vast and trunkless legs of stone',
          'Stand in the desert. . . . Near them, on the sand,',
          'Half sunk a shattered visage lies, whose frown,',
          'And wrinkled lip, and sneer of cold command,',
          'Tell that its sculptor well those passions read',
          'Which yet survive, stamped on these lifeless things,',
          'The hand that mocked them, and the heart that fed;',
          'And on the pedestal, these words appear:',
          'My name is Ozymandias, King of Kings;',
          'Look on my Works, ye Mighty, and despair!',
          'Nothing beside remains. Round the decay',
          'Of that colossal Wreck, boundless and bare',
          'The lone and level sands stretch far away."',
        ].join('\n'),
        caption: 'A sonnet on the ruins of empire.',
        mediaType: 'text',
        imageUrl: null,
        imageAlt: null,
        provenanceUrl: 'https://www.poetryfoundation.org/poems/46565/ozymandias',
      },
    ],
  },
  {
    externalKey: 'ap-lit-poetry-williams-red-wheelbarrow',
    frqType: 'poetry',
    title: '"The Red Wheelbarrow" — Poetry Analysis',
    prompt:
      "Read the following poem carefully. Then, in a well-written essay, analyze how Williams uses imagery, line breaks, and structure to invest an ordinary scene with significance.",
    focusSkill: 'imagery',
    difficulty: 'intro',
    skillEmphasis: 'thesis',
    defaultTimeMode: 'untimed',
    defaultDurationMinutes: 40,
    suggestedWorks: null,
    provenanceUrl: 'https://www.poetryfoundation.org/poems/45502/the-red-wheelbarrow',
    sources: [
      {
        externalKey: 'ap-lit-poetry-williams-red-wheelbarrow-poem',
        position: 1,
        title: 'The Red Wheelbarrow',
        attribution: 'William Carlos Williams, 1923 (public domain)',
        body: [
          'so much depends',
          'upon',
          '',
          'a red wheel',
          'barrow',
          '',
          'glazed with rain',
          'water',
          '',
          'beside the white',
          'chickens',
        ].join('\n'),
        caption: 'An imagist poem in sixteen words.',
        mediaType: 'text',
        imageUrl: null,
        imageAlt: null,
        provenanceUrl: 'https://www.poetryfoundation.org/poems/45502/the-red-wheelbarrow',
      },
    ],
  },
  {
    externalKey: 'ap-lit-poetry-shakespeare-sonnet-18',
    frqType: 'poetry',
    title: 'Sonnet 18 — Poetry Analysis',
    prompt:
      "Read the following poem carefully. Then, in a well-written essay, analyze how Shakespeare uses metaphor, structure, and the sonnet's turn to develop a claim about art and mortality.",
    focusSkill: 'figurative-language',
    difficulty: 'exam-ready',
    skillEmphasis: 'evidence-commentary',
    defaultTimeMode: 'untimed',
    defaultDurationMinutes: 40,
    suggestedWorks: null,
    provenanceUrl: 'https://www.poetryfoundation.org/poems/45087/sonnet-18-shall-i-compare-thee-to-a-summers-day',
    sources: [
      {
        externalKey: 'ap-lit-poetry-shakespeare-sonnet-18-poem',
        position: 1,
        title: 'Sonnet 18 ("Shall I compare thee to a summer\'s day?")',
        attribution: 'William Shakespeare, 1609 (public domain)',
        body: [
          "Shall I compare thee to a summer's day?",
          'Thou art more lovely and more temperate:',
          'Rough winds do shake the darling buds of May,',
          "And summer's lease hath all too short a date;",
          'Sometime too hot the eye of heaven shines,',
          "And often is his gold complexion dimm'd;",
          'And every fair from fair sometime declines,',
          "By chance or nature's changing course untrimm'd;",
          'But thy eternal summer shall not fade,',
          "Nor lose possession of that fair thou ow'st;",
          "Nor shall death brag thou wander'st in his shade,",
          "When in eternal lines to time thou grow'st:",
          'So long as men can breathe or eyes can see,',
          'So long lives this, and this gives life to thee.',
        ].join('\n'),
        caption: 'A sonnet on the permanence of verse.',
        mediaType: 'text',
        imageUrl: null,
        imageAlt: null,
        provenanceUrl: 'https://www.poetryfoundation.org/poems/45087/sonnet-18-shall-i-compare-thee-to-a-summers-day',
      },
    ],
  },

  // --- Prose fiction analysis (Q2) — public-domain passages ---
  {
    externalKey: 'ap-lit-prose-dickens-tale-of-two-cities-opening',
    frqType: 'prose',
    title: 'A Tale of Two Cities Opening — Prose Fiction Analysis',
    prompt:
      "Read the following passage carefully. Then, in a well-written essay, analyze how Dickens uses syntax, repetition, and antithesis to characterize the age he describes.",
    focusSkill: 'structure-and-syntax',
    difficulty: 'exam-ready',
    skillEmphasis: 'evidence-commentary',
    defaultTimeMode: 'untimed',
    defaultDurationMinutes: 40,
    suggestedWorks: null,
    provenanceUrl: 'https://www.gutenberg.org/ebooks/98',
    sources: [
      {
        externalKey: 'ap-lit-prose-dickens-tale-of-two-cities-opening-passage',
        position: 1,
        title: 'From A Tale of Two Cities, Book the First, Chapter 1',
        attribution: 'Charles Dickens, 1859 (public domain)',
        body:
          'It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair, we had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way—in short, the period was so far like the present period, that some of its noisiest authorities insisted on its being received, for good or for evil, in the superlative degree of comparison only.',
        caption: 'The novel\'s celebrated opening period.',
        mediaType: 'text',
        imageUrl: null,
        imageAlt: null,
        provenanceUrl: 'https://www.gutenberg.org/ebooks/98',
      },
    ],
  },
  {
    externalKey: 'ap-lit-prose-austen-emma-opening',
    frqType: 'prose',
    title: 'Emma Opening — Prose Fiction Analysis',
    prompt:
      "Read the following passage carefully. Then, in a well-written essay, analyze how Austen uses narrative voice and tone to characterize Emma and to hint at the novel's central irony.",
    focusSkill: 'characterization',
    difficulty: 'intro',
    skillEmphasis: 'thesis',
    defaultTimeMode: 'untimed',
    defaultDurationMinutes: 40,
    suggestedWorks: null,
    provenanceUrl: 'https://www.gutenberg.org/ebooks/158',
    sources: [
      {
        externalKey: 'ap-lit-prose-austen-emma-opening-passage',
        position: 1,
        title: 'From Emma, Volume 1, Chapter 1',
        attribution: 'Jane Austen, 1815 (public domain)',
        body: [
          'Emma Woodhouse, handsome, clever, and rich, with a comfortable home and happy disposition, seemed to unite some of the best blessings of existence; and had lived nearly twenty-one years in the world with very little to distress or vex her.',
          '',
          'She was the youngest of the two daughters of a most affectionate, indulgent father; and had, in consequence of her sister\'s marriage, been mistress of his house from a very early period. Her mother had died too long ago for her to have more than an indistinct remembrance of her caresses; and her place had been supplied by an excellent woman as governess, who had fallen little short of a mother in affection.',
        ].join('\n'),
        caption: 'The narrator introduces Emma.',
        mediaType: 'text',
        imageUrl: null,
        imageAlt: null,
        provenanceUrl: 'https://www.gutenberg.org/ebooks/158',
      },
    ],
  },
  {
    externalKey: 'ap-lit-prose-bronte-jane-eyre-opening',
    frqType: 'prose',
    title: 'Jane Eyre Opening — Prose Fiction Analysis',
    prompt:
      "Read the following passage carefully. Then, in a well-written essay, analyze how Brontë uses setting, weather, and the first-person voice to establish the young narrator's situation and state of mind.",
    focusSkill: 'setting-and-atmosphere',
    difficulty: 'exam-ready',
    skillEmphasis: 'sophistication',
    defaultTimeMode: 'untimed',
    defaultDurationMinutes: 40,
    suggestedWorks: null,
    provenanceUrl: 'https://www.gutenberg.org/ebooks/1260',
    sources: [
      {
        externalKey: 'ap-lit-prose-bronte-jane-eyre-opening-passage',
        position: 1,
        title: 'From Jane Eyre, Chapter 1',
        attribution: 'Charlotte Brontë, 1847 (public domain)',
        body:
          'There was no possibility of taking a walk that day. We had been wandering, indeed, in the leafless shrubbery an hour in the morning; but since dinner (Mrs. Reed, when there was no company, dined early) the cold winter wind had brought with it clouds so sombre, and a rain so penetrating, that further out-door exercise was now out of the question. I was glad of it: I never liked long walks, especially on chilly afternoons: dreadful to me was the coming home in the raw twilight, with nipped fingers and toes, and a heart saddened by the chidings of Bessie, the nurse, and humbled by the consciousness of my physical inferiority to Eliza, John, and Georgiana Reed.',
        caption: 'The novel opens on a cold, confined afternoon.',
        mediaType: 'text',
        imageUrl: null,
        imageAlt: null,
        provenanceUrl: 'https://www.gutenberg.org/ebooks/1260',
      },
    ],
  },

  // --- Literary argument (Q3) — open questions, no provided text ---
  {
    externalKey: 'ap-lit-argument-isolation',
    frqType: 'literary_argument',
    title: 'Isolation and Alienation — Literary Argument',
    prompt:
      "Many works of literature feature a character who is isolated or alienated from the society around them. Select a novel or play of literary merit in which such a character appears. Then, in a well-written essay, analyze how that isolation contributes to an interpretation of the work as a whole. Do not merely summarize the plot.",
    focusSkill: 'isolation',
    difficulty: 'exam-ready',
    skillEmphasis: 'sophistication',
    defaultTimeMode: 'untimed',
    defaultDurationMinutes: 40,
    suggestedWorks: [
      'The Catcher in the Rye — J. D. Salinger',
      'Frankenstein — Mary Shelley',
      'Invisible Man — Ralph Ellison',
      'The Metamorphosis — Franz Kafka',
    ].join('\n'),
    provenanceUrl: 'https://apcentral.collegeboard.org/courses/ap-english-literature-and-composition/exam',
    sources: [],
  },
  {
    externalKey: 'ap-lit-argument-minor-character',
    frqType: 'literary_argument',
    title: 'The Function of a Minor Character — Literary Argument',
    prompt:
      "In many works of literature, a minor character illuminates the meaning of the work far out of proportion to the character's time on the page. Select a novel or play of literary merit with such a character. Then, in a well-written essay, analyze how that minor character functions in the work as a whole. Do not merely summarize the plot.",
    focusSkill: 'minor-character',
    difficulty: 'exam-ready',
    skillEmphasis: 'evidence-commentary',
    defaultTimeMode: 'untimed',
    defaultDurationMinutes: 40,
    suggestedWorks: [
      'Jane Eyre — Charlotte Brontë',
      'Hamlet — William Shakespeare',
      'The Great Gatsby — F. Scott Fitzgerald',
      'Wuthering Heights — Emily Brontë',
    ].join('\n'),
    provenanceUrl: 'https://apcentral.collegeboard.org/courses/ap-english-literature-and-composition/exam',
    sources: [],
  },
  {
    externalKey: 'ap-lit-argument-haunted-by-the-past',
    frqType: 'literary_argument',
    title: 'Haunted by the Past — Literary Argument',
    prompt:
      "Many works of literature depict a character who cannot escape the past. Select a novel or play of literary merit in which the past exerts a powerful hold on a character. Then, in a well-written essay, analyze how the character's relationship to the past contributes to an interpretation of the work as a whole. Do not merely summarize the plot.",
    focusSkill: 'the-past',
    difficulty: 'exam-ready',
    skillEmphasis: 'sophistication',
    defaultTimeMode: 'untimed',
    defaultDurationMinutes: 40,
    suggestedWorks: [
      'Beloved — Toni Morrison',
      'The Great Gatsby — F. Scott Fitzgerald',
      'A Streetcar Named Desire — Tennessee Williams',
      'Wuthering Heights — Emily Brontë',
    ].join('\n'),
    provenanceUrl: 'https://apcentral.collegeboard.org/courses/ap-english-literature-and-composition/exam',
    sources: [],
  },
  {
    externalKey: 'ap-lit-argument-foil',
    frqType: 'literary_argument',
    title: 'The Role of a Foil — Literary Argument',
    prompt:
      "A foil is a character who, through contrast, reveals the distinctive qualities of another character. Select a novel or play of literary merit that uses a foil. Then, in a well-written essay, analyze how the foil relationship contributes to an interpretation of the work as a whole. Do not merely summarize the plot.",
    focusSkill: 'foil',
    difficulty: 'intro',
    skillEmphasis: 'evidence-commentary',
    defaultTimeMode: 'untimed',
    defaultDurationMinutes: 40,
    suggestedWorks: [
      'Hamlet — William Shakespeare',
      'Frankenstein — Mary Shelley',
      'Pride and Prejudice — Jane Austen',
      'Of Mice and Men — John Steinbeck',
    ].join('\n'),
    provenanceUrl: 'https://apcentral.collegeboard.org/courses/ap-english-literature-and-composition/exam',
    sources: [],
  },
  {
    externalKey: 'ap-lit-argument-central-symbol',
    frqType: 'literary_argument',
    title: 'A Central Symbol — Literary Argument',
    prompt:
      "Many works of literature use a recurring symbol to carry meaning. Select a novel or play of literary merit that develops a significant symbol. Then, in a well-written essay, analyze how the symbol contributes to an interpretation of the work as a whole. Do not merely summarize the plot.",
    focusSkill: 'symbol',
    difficulty: 'intro',
    skillEmphasis: 'thesis',
    defaultTimeMode: 'untimed',
    defaultDurationMinutes: 40,
    suggestedWorks: [
      'The Scarlet Letter — Nathaniel Hawthorne',
      'The Great Gatsby — F. Scott Fitzgerald',
      'Lord of the Flies — William Golding',
      'Their Eyes Were Watching God — Zora Neale Hurston',
    ].join('\n'),
    provenanceUrl: 'https://apcentral.collegeboard.org/courses/ap-english-literature-and-composition/exam',
    sources: [],
  },
  {
    externalKey: 'ap-lit-argument-individual-vs-society',
    frqType: 'literary_argument',
    title: 'The Individual Against Society — Literary Argument',
    prompt:
      "Many works of literature dramatize a conflict between an individual and the society or community around them. Select a novel or play of literary merit that stages such a conflict. Then, in a well-written essay, analyze how the conflict contributes to an interpretation of the work as a whole. Do not merely summarize the plot.",
    focusSkill: 'conflict-of-values',
    difficulty: 'exam-ready',
    skillEmphasis: 'evidence-commentary',
    defaultTimeMode: 'untimed',
    defaultDurationMinutes: 40,
    suggestedWorks: [
      'The Adventures of Huckleberry Finn — Mark Twain',
      'The Awakening — Kate Chopin',
      'A Doll\'s House — Henrik Ibsen',
      '1984 — George Orwell',
    ].join('\n'),
    provenanceUrl: 'https://apcentral.collegeboard.org/courses/ap-english-literature-and-composition/exam',
    sources: [],
  },
  {
    externalKey: 'ap-lit-argument-deception',
    frqType: 'literary_argument',
    title: 'Deception and Its Consequences — Literary Argument',
    prompt:
      "Many works of literature turn on an act of deception. Select a novel or play of literary merit in which deception plays a central role. Then, in a well-written essay, analyze how the deception contributes to an interpretation of the work as a whole. Do not merely summarize the plot.",
    focusSkill: 'deception',
    difficulty: 'exam-ready',
    skillEmphasis: 'evidence-commentary',
    defaultTimeMode: 'untimed',
    defaultDurationMinutes: 40,
    suggestedWorks: [
      'Othello — William Shakespeare',
      'The Crucible — Arthur Miller',
      'Great Expectations — Charles Dickens',
      'The Kite Runner — Khaled Hosseini',
    ].join('\n'),
    provenanceUrl: 'https://apcentral.collegeboard.org/courses/ap-english-literature-and-composition/exam',
    sources: [],
  },
  {
    externalKey: 'ap-lit-argument-journey',
    frqType: 'literary_argument',
    title: 'A Journey, Literal or Figurative — Literary Argument',
    prompt:
      "Many works of literature are structured around a journey, whether across a landscape or through an inner transformation. Select a novel or play of literary merit built around such a journey. Then, in a well-written essay, analyze how the journey contributes to an interpretation of the work as a whole. Do not merely summarize the plot.",
    focusSkill: 'journey',
    difficulty: 'intro',
    skillEmphasis: 'thesis',
    defaultTimeMode: 'untimed',
    defaultDurationMinutes: 40,
    suggestedWorks: [
      'Their Eyes Were Watching God — Zora Neale Hurston',
      'Heart of Darkness — Joseph Conrad',
      'The Adventures of Huckleberry Finn — Mark Twain',
      'Invisible Man — Ralph Ellison',
    ].join('\n'),
    provenanceUrl: 'https://apcentral.collegeboard.org/courses/ap-english-literature-and-composition/exam',
    sources: [],
  },
  {
    externalKey: 'ap-lit-argument-home-and-belonging',
    frqType: 'literary_argument',
    title: 'Home and Belonging — Literary Argument',
    prompt:
      "Many works of literature explore what it means to have — or to lose — a home. Select a novel or play of literary merit in which the idea of home is significant. Then, in a well-written essay, analyze how the treatment of home contributes to an interpretation of the work as a whole. Do not merely summarize the plot.",
    focusSkill: 'home-and-belonging',
    difficulty: 'intro',
    skillEmphasis: 'evidence-commentary',
    defaultTimeMode: 'untimed',
    defaultDurationMinutes: 40,
    suggestedWorks: [
      'A Raisin in the Sun — Lorraine Hansberry',
      'Their Eyes Were Watching God — Zora Neale Hurston',
      'Beloved — Toni Morrison',
      'The Namesake — Jhumpa Lahiri',
    ].join('\n'),
    provenanceUrl: 'https://apcentral.collegeboard.org/courses/ap-english-literature-and-composition/exam',
    sources: [],
  },
  {
    externalKey: 'ap-lit-argument-ambition',
    frqType: 'literary_argument',
    title: 'Ambition and Its Costs — Literary Argument',
    prompt:
      "Many works of literature examine a character driven by ambition. Select a novel or play of literary merit in which ambition shapes a character's fate. Then, in a well-written essay, analyze how the treatment of ambition contributes to an interpretation of the work as a whole. Do not merely summarize the plot.",
    focusSkill: 'ambition',
    difficulty: 'exam-ready',
    skillEmphasis: 'sophistication',
    defaultTimeMode: 'untimed',
    defaultDurationMinutes: 40,
    suggestedWorks: [
      'Macbeth — William Shakespeare',
      'The Great Gatsby — F. Scott Fitzgerald',
      'Frankenstein — Mary Shelley',
      'Wuthering Heights — Emily Brontë',
    ].join('\n'),
    provenanceUrl: 'https://apcentral.collegeboard.org/courses/ap-english-literature-and-composition/exam',
    sources: [],
  },
  {
    externalKey: 'ap-lit-argument-guilt-and-conscience',
    frqType: 'literary_argument',
    title: 'Guilt and Conscience — Literary Argument',
    prompt:
      "Many works of literature depict a character wrestling with guilt. Select a novel or play of literary merit in which guilt or conscience is central. Then, in a well-written essay, analyze how the character's guilt contributes to an interpretation of the work as a whole. Do not merely summarize the plot.",
    focusSkill: 'guilt',
    difficulty: 'exam-ready',
    skillEmphasis: 'evidence-commentary',
    defaultTimeMode: 'untimed',
    defaultDurationMinutes: 40,
    suggestedWorks: [
      'Crime and Punishment — Fyodor Dostoevsky',
      'Macbeth — William Shakespeare',
      'The Scarlet Letter — Nathaniel Hawthorne',
      'The Kite Runner — Khaled Hosseini',
    ].join('\n'),
    provenanceUrl: 'https://apcentral.collegeboard.org/courses/ap-english-literature-and-composition/exam',
    sources: [],
  },
  {
    externalKey: 'ap-lit-argument-power-and-corruption',
    frqType: 'literary_argument',
    title: 'Power and Corruption — Literary Argument',
    prompt:
      "Many works of literature explore how the pursuit or possession of power corrupts. Select a novel or play of literary merit in which power is a central concern. Then, in a well-written essay, analyze how the treatment of power contributes to an interpretation of the work as a whole. Do not merely summarize the plot.",
    focusSkill: 'power-and-corruption',
    difficulty: 'exam-ready',
    skillEmphasis: 'sophistication',
    defaultTimeMode: 'untimed',
    defaultDurationMinutes: 40,
    suggestedWorks: [
      'Macbeth — William Shakespeare',
      '1984 — George Orwell',
      'Animal Farm — George Orwell',
      'Lord of the Flies — William Golding',
    ].join('\n'),
    provenanceUrl: 'https://apcentral.collegeboard.org/courses/ap-english-literature-and-composition/exam',
    sources: [],
  },
  {
    externalKey: 'ap-lit-argument-sacrifice',
    frqType: 'literary_argument',
    title: 'Sacrifice — Literary Argument',
    prompt:
      "Many works of literature center on an act of sacrifice. Select a novel or play of literary merit in which a character sacrifices something of great value. Then, in a well-written essay, analyze how the sacrifice contributes to an interpretation of the work as a whole. Do not merely summarize the plot.",
    focusSkill: 'sacrifice',
    difficulty: 'intro',
    skillEmphasis: 'thesis',
    defaultTimeMode: 'untimed',
    defaultDurationMinutes: 40,
    suggestedWorks: [
      'A Tale of Two Cities — Charles Dickens',
      'Beloved — Toni Morrison',
      'Antigone — Sophocles',
      'The Kite Runner — Khaled Hosseini',
    ].join('\n'),
    provenanceUrl: 'https://apcentral.collegeboard.org/courses/ap-english-literature-and-composition/exam',
    sources: [],
  },
  {
    externalKey: 'ap-lit-argument-the-outsider',
    frqType: 'literary_argument',
    title: 'The Outsider — Literary Argument',
    prompt:
      "Many works of literature give voice to an outsider — a figure who does not belong to the world they inhabit. Select a novel or play of literary merit with such a figure. Then, in a well-written essay, analyze how the outsider's perspective contributes to an interpretation of the work as a whole. Do not merely summarize the plot.",
    focusSkill: 'the-outsider',
    difficulty: 'exam-ready',
    skillEmphasis: 'sophistication',
    defaultTimeMode: 'untimed',
    defaultDurationMinutes: 40,
    suggestedWorks: [
      'Frankenstein — Mary Shelley',
      'The Stranger — Albert Camus',
      'Invisible Man — Ralph Ellison',
      'Wuthering Heights — Emily Brontë',
    ].join('\n'),
    provenanceUrl: 'https://apcentral.collegeboard.org/courses/ap-english-literature-and-composition/exam',
    sources: [],
  },
  {
    externalKey: 'ap-lit-argument-freedom-vs-confinement',
    frqType: 'literary_argument',
    title: 'Freedom and Confinement — Literary Argument',
    prompt:
      "Many works of literature dramatize a character's struggle for freedom against forces that confine them. Select a novel or play of literary merit that stages this tension. Then, in a well-written essay, analyze how the tension between freedom and confinement contributes to an interpretation of the work as a whole. Do not merely summarize the plot.",
    focusSkill: 'freedom-vs-confinement',
    difficulty: 'exam-ready',
    skillEmphasis: 'evidence-commentary',
    defaultTimeMode: 'untimed',
    defaultDurationMinutes: 40,
    suggestedWorks: [
      'The Awakening — Kate Chopin',
      'A Doll\'s House — Henrik Ibsen',
      'Jane Eyre — Charlotte Brontë',
      'Their Eyes Were Watching God — Zora Neale Hurston',
    ].join('\n'),
    provenanceUrl: 'https://apcentral.collegeboard.org/courses/ap-english-literature-and-composition/exam',
    sources: [],
  },
  {
    externalKey: 'ap-lit-argument-mortality',
    frqType: 'literary_argument',
    title: 'The Awareness of Mortality — Literary Argument',
    prompt:
      "Many works of literature confront a character with the reality of death. Select a novel or play of literary merit in which the awareness of mortality is central. Then, in a well-written essay, analyze how that awareness contributes to an interpretation of the work as a whole. Do not merely summarize the plot.",
    focusSkill: 'mortality',
    difficulty: 'exam-ready',
    skillEmphasis: 'sophistication',
    defaultTimeMode: 'untimed',
    defaultDurationMinutes: 40,
    suggestedWorks: [
      'Hamlet — William Shakespeare',
      'A Farewell to Arms — Ernest Hemingway',
      'Beloved — Toni Morrison',
      'The Road — Cormac McCarthy',
    ].join('\n'),
    provenanceUrl: 'https://apcentral.collegeboard.org/courses/ap-english-literature-and-composition/exam',
    sources: [],
  },
  {
    externalKey: 'ap-lit-argument-identity',
    frqType: 'literary_argument',
    title: 'The Search for Identity — Literary Argument',
    prompt:
      "Many works of literature follow a character's search for a sense of self. Select a novel or play of literary merit in which the search for identity is central. Then, in a well-written essay, analyze how that search contributes to an interpretation of the work as a whole. Do not merely summarize the plot.",
    focusSkill: 'identity',
    difficulty: 'intro',
    skillEmphasis: 'thesis',
    defaultTimeMode: 'untimed',
    defaultDurationMinutes: 40,
    suggestedWorks: [
      'Invisible Man — Ralph Ellison',
      'The Bell Jar — Sylvia Plath',
      'Jane Eyre — Charlotte Brontë',
      'The Kite Runner — Khaled Hosseini',
    ].join('\n'),
    provenanceUrl: 'https://apcentral.collegeboard.org/courses/ap-english-literature-and-composition/exam',
    sources: [],
  },
  {
    externalKey: 'ap-lit-argument-parent-child',
    frqType: 'literary_argument',
    title: 'A Parent-Child Relationship — Literary Argument',
    prompt:
      "Many works of literature turn on the relationship between a parent and a child. Select a novel or play of literary merit in which such a relationship is significant. Then, in a well-written essay, analyze how the relationship contributes to an interpretation of the work as a whole. Do not merely summarize the plot.",
    focusSkill: 'family-relationships',
    difficulty: 'intro',
    skillEmphasis: 'evidence-commentary',
    defaultTimeMode: 'untimed',
    defaultDurationMinutes: 40,
    suggestedWorks: [
      'King Lear — William Shakespeare',
      'Beloved — Toni Morrison',
      'Fences — August Wilson',
      'The Namesake — Jhumpa Lahiri',
    ].join('\n'),
    provenanceUrl: 'https://apcentral.collegeboard.org/courses/ap-english-literature-and-composition/exam',
    sources: [],
  },
  {
    externalKey: 'ap-lit-argument-illusion-vs-reality',
    frqType: 'literary_argument',
    title: 'Illusion Versus Reality — Literary Argument',
    prompt:
      "Many works of literature explore the gap between illusion and reality. Select a novel or play of literary merit in which a character clings to an illusion. Then, in a well-written essay, analyze how the tension between illusion and reality contributes to an interpretation of the work as a whole. Do not merely summarize the plot.",
    focusSkill: 'illusion-vs-reality',
    difficulty: 'exam-ready',
    skillEmphasis: 'sophistication',
    defaultTimeMode: 'untimed',
    defaultDurationMinutes: 40,
    suggestedWorks: [
      'The Great Gatsby — F. Scott Fitzgerald',
      'A Streetcar Named Desire — Tennessee Williams',
      'Death of a Salesman — Arthur Miller',
      'Don Quixote — Miguel de Cervantes',
    ].join('\n'),
    provenanceUrl: 'https://apcentral.collegeboard.org/courses/ap-english-literature-and-composition/exam',
    sources: [],
  },
] as const;
