export const AP_HISTORY_LIBRARY_ENTRIES = [
  {
    externalKey: 'apush-dbq-new-deal-federal-power',
    course: 'apush',
    essayType: 'dbq',
    title: 'The New Deal and Federal Power',
    prompt:
      'Evaluate the extent to which the New Deal changed the role of the federal government in the United States.',
    period: '1932-1980',
    periodNumber: 7,
    reasoningSkill: 'causation',
    difficulty: 'exam-ready',
    skillEmphasis: 'evidence',
    defaultTimeMode: 'untimed',
    defaultDurationMinutes: 60,
    provenanceUrl: 'https://apcentral.collegeboard.org/',
    sources: [
      {
        externalKey: 'apush-dbq-new-deal-federal-power-doc-1',
        position: 1,
        title: 'Document 1',
        attribution: 'Franklin D. Roosevelt, first inaugural address, 1933',
        body: 'This Nation asks for action, and action now. Our greatest primary task is to put people to work.',
        caption: 'Roosevelt outlines federal response to economic crisis.',
        mediaType: 'text',
        imageUrl: null,
        imageAlt: null,
        provenanceUrl: 'https://apcentral.collegeboard.org/',
      },
      {
        externalKey: 'apush-dbq-new-deal-federal-power-doc-2',
        position: 2,
        title: 'Document 2',
        attribution: 'Social Security Act summary, 1935',
        body: 'The Act created old-age benefits and unemployment insurance funded through payroll taxes.',
        caption: 'Federal welfare-state expansion during the New Deal.',
        mediaType: 'text',
        imageUrl: null,
        imageAlt: null,
        provenanceUrl: 'https://apcentral.collegeboard.org/',
      },
    ],
  },
  {
    externalKey: 'apush-leq-market-revolution',
    course: 'apush',
    essayType: 'leq',
    title: 'The Market Revolution',
    prompt:
      'Evaluate the extent to which the Market Revolution transformed United States society in the period from 1815 to 1848.',
    period: '1815-1848',
    periodNumber: 4,
    reasoningSkill: 'causation',
    difficulty: 'intro',
    skillEmphasis: 'outside-evidence',
    defaultTimeMode: 'untimed',
    defaultDurationMinutes: 40,
    provenanceUrl: 'https://apcentral.collegeboard.org/',
    sources: [],
  },
  {
    externalKey: 'apush-leq-colonial-migration',
    course: 'apush',
    essayType: 'leq',
    title: `Causes of Colonial Migration`,
    prompt: `Evaluate the relative importance of causes of population movement to colonial British America in the period from 1607 to 1754. (Released 2022 APUSH LEQ #2)`,
    period: '1607-1754',
    periodNumber: 2,
    reasoningSkill: 'causation',
    difficulty: 'exam-ready',
    skillEmphasis: 'contextualization-heavy',
    defaultTimeMode: 'untimed',
    defaultDurationMinutes: 40,
    provenanceUrl: null,
    sources: [],
  },
  {
    externalKey: 'apush-leq-new-england-chesapeake',
    course: 'apush',
    essayType: 'leq',
    title: `New England and the Chesapeake`,
    prompt: `Evaluate the extent to which English colonial societies in the New England and Chesapeake regions prior to 1700 were similar to each other. (Released College Board APUSH Sample DBQ, 2018 CED — adapted as LEQ)`,
    period: '1607-1754',
    periodNumber: 2,
    reasoningSkill: 'comparison',
    difficulty: 'mid-year',
    skillEmphasis: 'complexity-heavy',
    defaultTimeMode: 'untimed',
    defaultDurationMinutes: 40,
    provenanceUrl: null,
    sources: [],
  },
  {
    externalKey: 'apush-dbq-american-independence',
    course: 'apush',
    essayType: 'dbq',
    title: `Ideas About American Independence, 1763–1783`,
    prompt: `Evaluate the extent of change in ideas about American independence from 1763 to 1783. (Released 2017 APUSH DBQ)`,
    period: '1754-1800',
    periodNumber: 3,
    reasoningSkill: 'continuity-and-change',
    difficulty: 'exam-ready',
    skillEmphasis: 'sourcing-heavy',
    defaultTimeMode: 'untimed',
    defaultDurationMinutes: 60,
    provenanceUrl: null,
    sources: [
      {
        externalKey: 'apush-dbq-american-independence-doc-1',
        position: 1,
        title: `Doc 1 — Virginia Resolves`,
        attribution: `The Virginia House of Burgesses, May 16, 1769, asserting the sole right of the colonial legislature to tax Virginians.`,
        body: `Resolved, That it is the Opinion of this Committee, that the sole Right of imposing Taxes on the Inhabitants of this his Majesty's Colony and Dominion of Virginia, is now, and ever hath been, legally and constitutionally vested in the House of Burgesses, lawfully convened according to the ancient and established Practice, with the Consent of the Council, and of his Majesty, the King of Great-Britain, or his Governor, for the Time being.

Resolved, That it is the Opinion of this Committee, that it is the undoubted Privilege of the Inhabitants of this Colony, to petition their Sovereign for Redress of Grievances; and that it is lawful and expedient to procure the Concurrence of his Majesty's other Colonies, in dutiful Addresses, praying the royal Interposition in Favour of the Violated Rights of America.

Resolved, That it is the Opinion of this Committee, that all Trials for Treason, Misprison of Treason, or for any Felony or Crime whatsoever, committed and done in this his Majesty's said Colony and Dominion, by any Person or Persons, residing in this Colony… and sending such Person, or Persons, to Places beyond the Sea, to be tried, is highly derogatory of the Rights of British Subjects.`,
        caption: null,
        mediaType: 'text',
        imageUrl: null,
        imageAlt: null,
        provenanceUrl: `https://teachingamericanhistory.org/document/the-virginia-resolves-of-1769/`,
      },
      {
        externalKey: 'apush-dbq-american-independence-doc-2',
        position: 2,
        title: `Doc 2 — Samuel Adams, Rights of the Colonists`,
        attribution: `Samuel Adams, writing for the Boston Committee of Correspondence, November 20, 1772 (the 'Boston Pamphlet').`,
        body: `Among the natural rights of the Colonists are these: First, a right to life; Secondly, to liberty; Thirdly, to property; together with the right to support and defend them in the best manner they can. These are evident branches of, rather than deductions from, the duty of self-preservation, commonly called the first law of nature.

All men have a right to remain in a state of nature as long as they please; and in case of intolerable oppression, civil or religious, to leave the society they belong to, and enter into another. When men enter into society, it is by voluntary consent; and they have a right to demand and insist upon the performance of such conditions and previous limitations as form an equitable original compact.

In short, it is the greatest absurdity to suppose it in the power of one, or any number of men, at the entering into society, to renounce their essential natural rights, or the means of preserving those rights; when the grand end of civil government, from the very nature of its institution, is for the support, protection, and defence of those very rights; the principal of which, as is before observed, are Life, Liberty, and Property.`,
        caption: null,
        mediaType: 'text',
        imageUrl: null,
        imageAlt: null,
        provenanceUrl: `https://americainclass.org/sources/makingrevolution/crisis/text6/bostonpamphlet.pdf`,
      },
      {
        externalKey: 'apush-dbq-american-independence-doc-3',
        position: 3,
        title: `Doc 3 — Quaker Testimony`,
        attribution: `The Religious Society of Friends (Quakers), Pennsylvania and New Jersey Meeting at Philadelphia, January 24, 1775.`,
        body: `HAVING considered with real sorrow, the unhappy contest between the legislature of Great Britain and the people of these Colonies, and the animosities consequent thereon; we have by repeated public advices and private admonitions, used our endeavours to dissuade the members of our religious society from joining with the public resolutions promoted and entered into by some of the people, which as we apprehended, so we now find have increased contention, and produced great discord and confusion.

The Divine Principle of Grace and Truth which we profess, leads all who attend to its dictates, to demean themselves as peaceable subjects, and to discountenance and avoid every measure tending to excite disaffection to the King, as supreme magistrate, or to the legal authority of his government.

May we therefore firmly unite in the abhorrence of all such writings, and measures, as evince a desire and design to break off the happy connection we have heretofore enjoyed, with the kingdom of Great Britain, and our just and necessary subordination to the King and those who are lawfully placed in authority under him.`,
        caption: null,
        mediaType: 'text',
        imageUrl: null,
        imageAlt: null,
        provenanceUrl: `https://www.loc.gov/resource/rbpe.1440320b/?sp=1&st=text`,
      },
      {
        externalKey: 'apush-dbq-american-independence-doc-4',
        position: 4,
        title: `Doc 4 — Janet Schaw, Journal of a Lady of Quality`,
        attribution: `Janet Schaw, a Scottish loyalist visiting her brother's plantation near Wilmington, North Carolina, June 1775.`,
        body: `At present the martial law stands thus: An officer or committeeman enters a plantation with his posse. The Alternative is proposed: Agree to join us, and your persons and properties are safe. You have a shilling sterling a day; your duty is no more than once a month appearing under Arms at Wilmingtown, which will prove only a merry-making, where you will have as much grog as you can drink. But if you refuse, we are directly to cut up your corn, shoot your pigs, burn your houses, seize your Negroes, and perhaps tar and feather yourself.

Not to choose the first requires more courage than they are possessed of, and I believe this method has seldom failed with the lower sort. No sooner do they appear under arms on the stated day, than they are harangued by their officers with the implacable cruelty of the king of Great Britain, who has resolved to take their property from them, and to deprive them of their Charter rights.

Everything here is in the utmost confusion. Committees are appointed to inspect into the Characters and Conduct of every tradesman, to prevent them selling Tea or buying British Manufactures. Some of them have been tarred and feathered, others had their property burnt and destroyed by the populace.`,
        caption: null,
        mediaType: 'text',
        imageUrl: null,
        imageAlt: null,
        provenanceUrl: `https://americainclass.org/wp-content/uploads/2012/06/schaw-journal.pdf`,
      },
      {
        externalKey: 'apush-dbq-american-independence-doc-5',
        position: 5,
        title: `Doc 5 — Charles Inglis, True Interest of America`,
        attribution: `Rev. Charles Inglis, Anglican loyalist clergyman at Trinity Church in New York City, replying to Paine's Common Sense, 1776.`,
        body: `This melancholy contest would last till one side conquered. Supposing Britain to be victorious; however high my opinion is of British Generosity, I should be exceedingly sorry to receive terms from her in the haughty tone of a conqueror. Or supposing such a failure of her manufactures, commerce and strength, that victory should incline to the side of America; yet who can say in that case, what extremities her sense of resentment and self-preservation will drive Great-Britain to?

For my part, I should not in the least be surprized, if on such a prospect as the Independency of America, she would parcel out this continent to the different European Powers. Canada might be restored to France, Florida to Spain, with additions to each—other states also might come in for a portion. Let no man think this chimerical or improbable. The independency of America would be so fatal to Britain, that she would leave nothing in her power undone to prevent it.

By a connection with Great-Britain, our trade would still have the protection of the greatest naval power in the world… What an exhaustless fund of wealth would Britain become to America, who shares its commerce!`,
        caption: null,
        mediaType: 'text',
        imageUrl: null,
        imageAlt: null,
        provenanceUrl: `https://www.let.rug.nl/usa/documents/1776-1785/charles-inglis-the-true-interest-of-america-impartially-stated-1776.php`,
      },
      {
        externalKey: 'apush-dbq-american-independence-doc-6',
        position: 6,
        title: `Doc 6 — Thomas Paine, The American Crisis`,
        attribution: `Thomas Paine, The American Crisis No. 1, published in the Pennsylvania Journal, December 19, 1776, during Washington's retreat across the Delaware.`,
        body: `THESE are the times that try men's souls. The summer soldier and the sunshine patriot will, in this crisis, shrink from the service of their country; but he that stands it now, deserves the love and thanks of man and woman. Tyranny, like hell, is not easily conquered; yet we have this consolation with us, that the harder the conflict, the more glorious the triumph. What we obtain too cheap, we esteem too lightly: it is dearness only that gives every thing its value. Heaven knows how to put a proper price upon its goods; and it would be strange indeed if so celestial an article as FREEDOM should not be highly rated.

Britain, with an army to enforce her tyranny, has declared that she has a right (not only to TAX) but "to BIND us in ALL CASES WHATSOEVER," and if being bound in that manner, is not slavery, then is there not such a thing as slavery upon earth. Even the expression is impious; for so unlimited a power can belong only to God.

Not all the treasures of the world, so far as I believe, could have induced me to support an offensive war, for I think it murder; but if a thief breaks into my house, burns and destroys my property, and kills or threatens to kill me, or those that are in it… am I to suffer it?`,
        caption: null,
        mediaType: 'text',
        imageUrl: null,
        imageAlt: null,
        provenanceUrl: `https://www.gutenberg.org/files/3741/3741-h/3741-h.htm`,
      },
    ],
  },
  {
    externalKey: 'apush-dbq-articles-confederation',
    course: 'apush',
    essayType: 'dbq',
    title: `From the Articles of Confederation to the Constitution`,
    prompt: `Evaluate the extent to which weaknesses of the Articles of Confederation led to the drafting and adoption of the United States Constitution from 1781 to 1788.`,
    period: '1754-1800',
    periodNumber: 3,
    reasoningSkill: 'causation',
    difficulty: 'mid-year',
    skillEmphasis: 'complexity-heavy',
    defaultTimeMode: 'untimed',
    defaultDurationMinutes: 60,
    provenanceUrl: null,
    sources: [
      {
        externalKey: 'apush-dbq-articles-confederation-doc-1',
        position: 1,
        title: `Doc 1 — Washington to Knox on Shays' Rebellion`,
        attribution: `George Washington, letter to Henry Knox, Mount Vernon, February 3, 1787. Washington was at Mount Vernon when Shays' Rebellion erupted.`,
        body: `I feel my self exceedingly obliged to you for the full, & friendly communications in your letters of the 14th 21st & 25th ult.; and shall (critically as matters are described in the latter) be extremely anxious to know the issue of the movements of the forces that were assembling, the one to support, the other to oppose the constitutional rights of Massachusetts. The moment is, indeed, important!

If government shrinks, or is unable to enforce its laws; fresh manœuvres will be displayed by the insurgents—anarchy & confusion must prevail—and every thing will be turned topsy turvey in that State; where it is not probable the mischiefs will terminate.

In your letter of the 14th you express a wish to know my intention respecting the Convention, proposed to be held at Philada in May next. In confidence I inform you, that it is not, at this time, my purpose to attend it.

[I am] indeed, after what I have seen, or rather after what I have heard, I shall be surprized at nothing; for if three years ago, any person had told me that at this day, I should see such a formidable rebellion against the laws & constitutions of our own making as now appears I should have thought him a bedlamite—a fit subject for a mad house.`,
        caption: null,
        mediaType: 'text',
        imageUrl: null,
        imageAlt: null,
        provenanceUrl: `https://founders.archives.gov/documents/Washington/04-05-02-0006`,
      },
      {
        externalKey: 'apush-dbq-articles-confederation-doc-2',
        position: 2,
        title: `Doc 2 — Knox to Washington on the Rebels`,
        attribution: `Henry Knox, Secretary of War, letter to George Washington, October 23, 1786, reporting on the spreading unrest in western Massachusetts.`,
        body: `Their creed is "That the property of the United States, has been protected from the confiscations of Britain by the joint exertions of all, and therefore ought to be the common property of all. And he that attempts opposition to this creed is an enemy to equity and justice, & ought to be swept from off the face of the earth."

In a word they are determined to annihilate all debts public and private and have agrarian Laws which are easily effected by means of unfunded paper money which shall be a tender in all cases whatever.

The numbers of these people may amount in [M]assachusetts to about one fifth part of several populous counties, and to them may be collected, people of similar sentiments, from the States of Rhode Island, Connecticut and New Hampshire so as to constitute a body of 12 or 15,000 desperate and unprincipled men—They are chiefly of the Young and active part of the community.

This dreadful situation has alarmed every man of principle and property in New England—They start as from a dream, and ask what has been the Cause of our delusion? What is to give us security against the violence of lawless men?—Our government must be braced, changed, or altered to secure our lives and property.`,
        caption: null,
        mediaType: 'text',
        imageUrl: null,
        imageAlt: null,
        provenanceUrl: `https://www.historyisaweapon.com/defcon1/knoxwashington.html`,
      },
      {
        externalKey: 'apush-dbq-articles-confederation-doc-3',
        position: 3,
        title: `Doc 3 — Madison, Vices of the Political System`,
        attribution: `James Madison, memorandum prepared in April 1787 in advance of the Constitutional Convention. Madison enumerated the structural failures of the Articles of Confederation.`,
        body: `1. Failure of the States to comply with the Constitutional requisitions.

This evil has been so fully experienced both during the war and since the peace, results so naturally from the number and independent authority of the States and has been so uniformly examplified in every similar Confederacy, that it may be considered as not less radically and permanently inherent in, than it is fatal to the object of, the present System.

7. Want of sanction to the laws, and of coercion in the Government of the Confederacy.

A sanction is essential to the idea of law, as coercion is to that of Government. The federal system being destitute of both, wants the great vital principles of a Political Cons[ti]tution. Under the form of such a Constitution, it is in fact nothing more than a treaty of amity of commerce and of alliance, between so many independent and Sovereign States.

11. Injustice of the laws of the States.

If the multiplicity and mutability of laws prove a want of wisdom, their injustice betrays a defect still more alarming: more alarming not merely because it is a greater evil in itself, but because it brings more into question the fundamental principle of republican Government, that the majority who rule in such Governments, are the safest Guardians both of public Good and of private rights.`,
        caption: null,
        mediaType: 'text',
        imageUrl: null,
        imageAlt: null,
        provenanceUrl: `https://founders.archives.gov/documents/Madison/01-09-02-0187`,
      },
      {
        externalKey: 'apush-dbq-articles-confederation-doc-4',
        position: 4,
        title: `Doc 4 — Madison, Federalist No. 10`,
        attribution: `James Madison, writing as 'Publius,' Federalist No. 10, published in the New-York Packet, November 22, 1787, defending the proposed Constitution.`,
        body: `Among the numerous advantages promised by a well constructed union, none deserves to be more accurately developed than its tendency to break and control the violence of faction. The friend of popular governments, never finds himself so much alarmed for their character and fate, as when he contemplates their propensity to this dangerous vice.

By a faction, I understand a number of citizens, whether amounting to a majority or minority of the whole, who are united and actuated by some common impulse of passion, or of interest, adverse to the rights of other citizens, or to the permanent and aggregate interests of the community.

The latent causes of faction are thus sown in the nature of man… The most common and durable source of factions, has been the various and unequal distribution of property.

A rage for paper money, for an abolition of debts, for an equal division of property, or for any other improper or wicked project, will be less apt to pervade the whole body of the Union than a particular member of it; in the same proportion as such a malady is more likely to taint a particular county or district, than an entire State.

In the extent and proper structure of the Union, therefore, we behold a republican remedy for the diseases most incident to republican government.`,
        caption: null,
        mediaType: 'text',
        imageUrl: null,
        imageAlt: null,
        provenanceUrl: `https://founders.archives.gov/documents/Madison/01-10-02-0178`,
      },
      {
        externalKey: 'apush-dbq-articles-confederation-doc-5',
        position: 5,
        title: `Doc 5 — Brutus No. 1`,
        attribution: `Robert Yates (writing as 'Brutus'), Anti-Federalist essay published in the New-York Journal, October 18, 1787, opposing ratification of the Constitution.`,
        body: `If respect is to be paid to the opinion of the greatest and wisest men who have ever thought or wrote on the science of government, we shall be constrained to conclude, that a free republic cannot succeed over a country of such immense extent, containing such a number of inhabitants…

It is natural to a republic to have only a small territory, otherwise it cannot long subsist. In a large republic there are men of large fortunes, and consequently of less moderation; there are trusts too great to be placed in any single subject; he has interest of his own; he soon begins to think that he may be happy, great and glorious, by oppressing his fellow citizens; and that he may raise himself to grandeur on the ruins of his country.

The territory of the United States is of vast extent; it now contains near three millions of souls, and is capable of containing much more than ten times that number. Is it practicable for a country, so large and so numerous as they will soon become, to elect a representation, that will speak their sentiments, without their becoming so numerous as to be incapable of transacting public business? It certainly is not.

These are some of the reasons by which it appears, that a free republic cannot long subsist over a country of the great extent of these states. If then this new constitution is calculated to consolidate the thirteen states into one, as it evidently is, it ought not to be adopted.`,
        caption: null,
        mediaType: 'text',
        imageUrl: null,
        imageAlt: null,
        provenanceUrl: `https://minio.la.utexas.edu/webeditor-files/coretexts/pdf/178720brutus201.pdf`,
      },
    ],
  },
  {
    externalKey: 'apush-dbq-federal-power-1790s',
    course: 'apush',
    essayType: 'dbq',
    title: `Debates Over Federal Power, 1789–1800`,
    prompt: `Evaluate the extent to which debates over the proper scope of federal power shaped American politics in the period from 1789 to 1800.`,
    period: '1754-1800',
    periodNumber: 3,
    reasoningSkill: 'comparison',
    difficulty: 'exam-ready',
    skillEmphasis: 'sourcing-heavy',
    defaultTimeMode: 'untimed',
    defaultDurationMinutes: 60,
    provenanceUrl: null,
    sources: [
      {
        externalKey: 'apush-dbq-federal-power-1790s-doc-1',
        position: 1,
        title: `Doc 1 — Hamilton, Report on Public Credit`,
        attribution: `Alexander Hamilton, Secretary of the Treasury, First Report on Public Credit, submitted to Congress January 9, 1790, proposing federal assumption of state Revolutionary War debts.`,
        body: `While the observance of that good faith, which is the basis of public credit, is recommended by the strongest inducements of political expediency, it is enforced by considerations of still greater authority. There are arguments for it, which rest on the immutable principles of moral obligation… This reflection derives additional strength from the nature of the debt of the United States. It was the price of liberty.

The Secretary, after mature reflection on this point, entertains a full conviction that an assumption of the debts of the particular states by the Union, and a like provision for them as for those of the Union, will be a measure of sound policy and substantial justice. It would, in the opinion of the Secretary, contribute, in an eminent degree, to an orderly, stable and satisfactory arrangement of the national finances.

It is a well known fact that in countries in which the national debt is properly funded and an object of established confidence, it answers most of the purposes of money. Transfers of stock or public debt are there equivalent to payments in specie… Trade is extended by it; because there is a larger capital to carry it on, and the merchant can at the same time afford to trade for smaller profits.`,
        caption: null,
        mediaType: 'text',
        imageUrl: null,
        imageAlt: null,
        provenanceUrl: `https://teachingamericanhistory.org/document/first-report-on-public-credit/`,
      },
      {
        externalKey: 'apush-dbq-federal-power-1790s-doc-2',
        position: 2,
        title: `Doc 2 — Jefferson, Opinion on the Bank`,
        attribution: `Thomas Jefferson, Secretary of State, Opinion on the Constitutionality of a National Bank, February 15, 1791, submitted to President Washington.`,
        body: `I consider the foundation of the Constitution as laid on this ground: That "all powers not delegated to the United States, by the Constitution, nor prohibited by it to the States, are reserved to the States or to the people." To take a single step beyond the boundaries thus specially drawn around the powers of Congress, is to take possession of a boundless field of power, no longer susceptible of any definition.

The incorporation of a bank, and the powers assumed by this bill, have not, in my opinion, been delegated to the United States, by the Constitution.

They are not among the powers specially enumerated: for these are: 1st A power to lay taxes for the purpose of paying the debts of the United States; but no debt is paid by this bill, nor any tax laid. Were it a bill to raise money, its origination in the Senate would condemn it by the Constitution.

2. 'to borrow money.' But this bill neither borrows money nor ensures the borrowing of it…

The second general phrase is, 'to make all laws necessary and proper for carrying into execution the enumerated powers.' But they can all be carried into execution without a bank. A bank therefore is not necessary, and consequently not authorized by this phrase.`,
        caption: null,
        mediaType: 'text',
        imageUrl: null,
        imageAlt: null,
        provenanceUrl: `https://founders.archives.gov/documents/Jefferson/01-19-02-0051`,
      },
      {
        externalKey: 'apush-dbq-federal-power-1790s-doc-3',
        position: 3,
        title: `Doc 3 — Hamilton, Opinion on the Bank`,
        attribution: `Alexander Hamilton, Secretary of the Treasury, Opinion on the Constitutionality of an Act to Establish a Bank, February 23, 1791, defending the bank to President Washington.`,
        body: `Now it appears to the Secretary of the Treasury that this general principle is inherent in the very definition of Government and essential to every step of the progress to be made by that of the United States; namely—that every power vested in a Government is in its nature sovereign, and includes by force of the term, a right to employ all the means requisite, and fairly applicable to the attainment of the ends of such power; and which are not precluded by restrictions & exceptions specified in the constitution; or not immoral, or not contrary to the essential ends of political society.

This principle in its application to Government in general would be admitted as an axiom… The means by which national exigencies are to be provided for, national inconveniencies obviated, national prosperity promoted, are of such infinite variety, extent and complexity, that there must, of necessity, be great latitude of discretion in the selection & application of those means.

It is essential to the being of the National government, that so erroneous a conception of the meaning of the word necessary, should be exploded. It is certain that neither the grammatical, nor popular sense of the term requires that construction. According to both, necessary often means no more than needful, requisite, incidental, useful, or conducive to.`,
        caption: null,
        mediaType: 'text',
        imageUrl: null,
        imageAlt: null,
        provenanceUrl: `https://hamilton.gilderlehrman.org/supporting-document/hamilton-constitutionality-national-bank-1791`,
      },
      {
        externalKey: 'apush-dbq-federal-power-1790s-doc-4',
        position: 4,
        title: `Doc 4 — Washington's Farewell Address`,
        attribution: `George Washington, Farewell Address, published in the American Daily Advertiser, September 19, 1796, as Washington declined a third term.`,
        body: `I have already intimated to you the danger of parties in the State, with particular reference to the founding of them on geographical discriminations. Let me now take a more comprehensive view, and warn you in the most solemn manner against the baneful effects of the spirit of party generally.

This spirit, unfortunately, is inseparable from our nature, having its root in the strongest passions of the human mind… It serves always to distract the public councils and enfeeble the public administration. It agitates the community with ill-founded jealousies and false alarms; kindles the animosity of one part against another; foments occasionally riot and insurrection.

The great rule of conduct for us in regard to foreign nations is, in extending our commercial relations to have with them as little political connection as possible. So far as we have already formed engagements let them be fulfilled with perfect good faith. Here let us stop.

Why forego the advantages of so peculiar a situation? Why quit our own to stand upon foreign ground? Why, by interweaving our destiny with that of any part of Europe, entangle our peace and prosperity in the toils of European ambition, rivalship, interest, humor or caprice? It is our true policy to steer clear of permanent alliances with any portion of the foreign world.`,
        caption: null,
        mediaType: 'text',
        imageUrl: null,
        imageAlt: null,
        provenanceUrl: `https://avalon.law.yale.edu/18th_century/washing.asp`,
      },
    ],
  },
  {
    externalKey: 'apush-leq-seven-years-war-turning-point',
    course: 'apush',
    essayType: 'leq',
    title: `The Seven Years' War as a Turning Point`,
    prompt: `Evaluate the extent to which the Seven Years' War (French and Indian War, 1754–1763) marked a turning point in American relations with Great Britain, analyzing what changed and what stayed the same from the period before the war to the period after it. (Released 2015 APUSH LEQ #2)`,
    period: '1754-1800',
    periodNumber: 3,
    reasoningSkill: 'periodization',
    difficulty: 'exam-ready',
    skillEmphasis: 'complexity-heavy',
    defaultTimeMode: 'untimed',
    defaultDurationMinutes: 40,
    provenanceUrl: null,
    sources: [],
  },
  {
    externalKey: 'apush-leq-self-government-colonial',
    course: 'apush',
    essayType: 'leq',
    title: `Self-Government and Imperial Authority`,
    prompt: `Evaluate the extent to which ideas of self-government influenced American colonial reaction to British imperial authority in the period from 1754 to 1776. (Released 2019 APUSH LEQ #2)`,
    period: '1754-1800',
    periodNumber: 3,
    reasoningSkill: 'causation',
    difficulty: 'mid-year',
    skillEmphasis: 'contextualization-heavy',
    defaultTimeMode: 'untimed',
    defaultDurationMinutes: 40,
    provenanceUrl: null,
    sources: [],
  },
  {
    externalKey: 'apush-dbq-civil-war-reconstruction',
    course: 'apush',
    essayType: 'dbq',
    title: 'Civil War & Reconstruction',
    prompt: `Evaluate the extent to which the Civil War and Reconstruction changed the social and political status of African Americans in the period from 1861 to 1877.`,
    period: '1861-1877',
    periodNumber: 5,
    reasoningSkill: 'continuity-and-change',
    difficulty: 'exam-ready',
    skillEmphasis: 'sourcing-heavy',
    defaultTimeMode: 'untimed',
    defaultDurationMinutes: 60,
    provenanceUrl: 'https://www.loc.gov/',
    sources: [
      {
        externalKey: 'apush-dbq-civil-war-reconstruction-doc-1',
        position: 1,
        title: 'Doc 1 — Emancipation Proclamation',
        attribution: `Abraham Lincoln, Emancipation Proclamation, January 1, 1863.`,
        body: `I do order and declare that all persons held as slaves within said designated States, and parts of States, are, and henceforward shall be free; and that the Executive government of the United States, including the military and naval authorities thereof, will recognize and maintain the freedom of said persons.

And I hereby enjoin upon the people so declared to be free to abstain from all violence, unless in necessary self-defence; and I recommend to them that, in all cases when allowed, they labor faithfully for reasonable wages.

And I further declare and make known, that such persons of suitable condition, will be received into the armed service of the United States to garrison forts, positions, stations, and other places, and to man vessels of all sorts in said service.`,
        caption: null,
        mediaType: 'text',
        imageUrl: null,
        imageAlt: null,
        provenanceUrl: null,
      },
      {
        externalKey: 'apush-dbq-civil-war-reconstruction-doc-2',
        position: 2,
        title: 'Doc 2 — A Black soldier writes to Lincoln',
        attribution: `Corporal James Henry Gooding, a Black soldier in the 54th Massachusetts Volunteer Infantry, letter to President Abraham Lincoln, September 28, 1863.`,
        body: `Now the main question is, are we Soldiers, or are we Labourers? We are fully armed, and equipped, have done all the various Duties pertaining to a Soldier's life, have conducted ourselves to the complete satisfaction of General Officers. . . . We have shared the perils and labour of reducing the first stronghold that flaunted a Traitor Flag; and more, Mr. President, today the Anglo-Saxon Mother, Wife, or Sister are not alone in tears for departed Sons, Husbands and Brothers. . . . Now your Excellency, we have done a Soldier's Duty. Why can't we have a Soldier's pay?`,
        caption: null,
        mediaType: 'text',
        imageUrl: null,
        imageAlt: null,
        provenanceUrl: null,
      },
      {
        externalKey: 'apush-dbq-civil-war-reconstruction-doc-3',
        position: 3,
        title: 'Doc 3 — Mississippi Black Codes',
        attribution: `Mississippi Black Codes, laws passed by the state legislature, November 1865.`,
        body: `Every civil officer shall, and every person may, arrest and carry back to his or her legal employer any freedman, free negro, or mulatto who shall have quit the service of his or her employer before the expiration of his or her term of service without good cause. . . .

All freedmen, free negroes and mulattoes in this State, over the age of eighteen years, found on the second Monday in January, 1866, or thereafter, with no lawful employment or business, or found unlawfully assembling themselves together, either in the day or night time . . . shall be deemed vagrants, and on conviction thereof shall be fined.`,
        caption: null,
        mediaType: 'text',
        imageUrl: null,
        imageAlt: null,
        provenanceUrl: null,
      },
      {
        externalKey: 'apush-dbq-civil-war-reconstruction-doc-4',
        position: 4,
        title: 'Doc 4 — Anti–Freedmen’s Bureau broadside',
        attribution: `Broadside published in Pennsylvania during the congressional campaign of 1866, attacking the Freedmen's Bureau and Radical Republicans in Congress.`,
        body: `A racist campaign broadside. A caricatured Black man reclines idly in the foreground while white men labor in the background. The headline reads: "The Freedman's Bureau! An agency to keep the Negro in idleness at the expense of the White man. Twice vetoed by the President, and made a law by Congress." Side panels contrast "The White Man" who "must Work" to pay taxes with the "Freedman's Bureau" that dispenses relief, urging voters: "Support Congress & you support the Negro. Sustain the President & you protect the White man."`,
        caption: `Political broadside, Pennsylvania, 1866 (Library of Congress).`,
        mediaType: 'image',
        imageUrl: null,
        imageAlt: `1866 Pennsylvania campaign broadside caricaturing a Black man as idle while white men work, attacking the Freedmen's Bureau and Radical Republicans in Congress.`,
        provenanceUrl: 'https://www.loc.gov/',
      },
      {
        externalKey: 'apush-dbq-civil-war-reconstruction-doc-5',
        position: 5,
        title: 'Doc 5 — “The First Vote”',
        attribution: `Alfred R. Waud, "The First Vote," engraving published in Harper's Weekly, November 16, 1867, depicting freedmen voting in a Southern state election under the Reconstruction Acts.`,
        body: `A wood engraving showing a line of Black men waiting to cast ballots at a polling window. At the front, a well-dressed elderly craftsman deposits his ballot; behind him stand a businessman and a Union Army veteran in uniform, representing a cross-section of the newly enfranchised freedmen exercising the franchise granted under the Reconstruction Acts.`,
        caption: `Harper's Weekly, November 16, 1867 (Library of Congress).`,
        mediaType: 'image',
        imageUrl: null,
        imageAlt: `Alfred R. Waud's 1867 engraving "The First Vote," showing freedmen — a craftsman, a businessman, and a Union soldier — lined up to cast their first ballots.`,
        provenanceUrl: 'https://www.loc.gov/',
      },
      {
        externalKey: 'apush-dbq-civil-war-reconstruction-doc-6',
        position: 6,
        title: 'Doc 6 — Abram Colby testimony',
        attribution: `Abram Colby, a formerly enslaved member of the Georgia state legislature, testimony before a joint congressional committee investigating Ku Klux Klan violence, 1872.`,
        body: `On the 29th of October, 1869, they broke my door open, took me out of bed, took me to the woods and whipped me three hours or more and left me for dead. They said to me, "Do you think you will ever vote another damned Radical ticket?" I said, "If there was an election tomorrow, I would vote the Radical ticket." They set in and whipped me a thousand licks more, with sticks and straps that had buckles on the ends of them. . . . They said I had voted for Grant and had carried the Negroes against them. No man can make a free speech in my county. I do not believe it can be done anywhere in Georgia.`,
        caption: null,
        mediaType: 'text',
        imageUrl: null,
        imageAlt: null,
        provenanceUrl: null,
      },
      {
        externalKey: 'apush-dbq-civil-war-reconstruction-doc-7',
        position: 7,
        title: 'Doc 7 — Frederick Douglass',
        attribution: `Frederick Douglass, speech delivered at the unveiling of the Freedmen's Monument, Washington, D.C., April 14, 1876.`,
        body: `We have been, and are yet to be, tried by our friends as well as by our enemies. . . . You say you have emancipated us. You have; and I thank you for it. You say you have enfranchised us. You have; and I thank you for it. But what is your emancipation?—what is your enfranchisement? What does it all amount to, if the black man, after having been made free by the letter of your law, is unable to exercise that freedom, and, after having been freed from the slaveholder's lash, he is to be subject to the slaveholder's shot-gun?`,
        caption: null,
        mediaType: 'text',
        imageUrl: null,
        imageAlt: null,
        provenanceUrl: null,
      },
    ],
  },
  {
    externalKey: 'apush-dbq-gilded-age',
    course: 'apush',
    essayType: 'dbq',
    title: 'The Gilded Age',
    prompt: `Evaluate the extent to which the rise of industrial capitalism changed the relationship between American workers and their employers in the period from 1870 to 1900.`,
    period: '1870-1900',
    periodNumber: 6,
    reasoningSkill: 'continuity-and-change',
    difficulty: 'exam-ready',
    skillEmphasis: 'evidence',
    defaultTimeMode: 'untimed',
    defaultDurationMinutes: 60,
    provenanceUrl: 'https://www.loc.gov/',
    sources: [
      {
        externalKey: 'apush-dbq-gilded-age-doc-1',
        position: 1,
        title: 'Doc 1 — Knights of Labor preamble',
        attribution: `Preamble to the constitution of the Knights of Labor, 1878.`,
        body: `The alarming development and aggressiveness of great capitalists and corporations, unless checked, will inevitably lead to the pauperization and hopeless degradation of the toiling masses. It is imperative, if we desire to enjoy the full blessings of life, that a check be placed upon unjust accumulation, and the power for evil of aggregated wealth. . . . Therefore we have formed the Order of Knights of Labor, for the purpose of organizing and directing the power of the industrial masses . . . to secure to the workers the full enjoyment of the wealth they create, sufficient leisure in which to develop their intellectual, moral and social faculties.`,
        caption: null,
        mediaType: 'text',
        imageUrl: null,
        imageAlt: null,
        provenanceUrl: null,
      },
      {
        externalKey: 'apush-dbq-gilded-age-doc-2',
        position: 2,
        title: 'Doc 2 — A machinist testifies',
        attribution: `John Morrison, a machinist, testimony before the United States Senate Committee on the Relations between Labor and Capital, 1883.`,
        body: `Well, the trade has been subdivided and those subdivisions have been again subdivided, so that a man never learns the machinist's trade now. Ten years ago he learned, not the whole of the trade, but a fair portion of it. . . . In the case of making the sewing-machine, for instance, you find that the trade is so subdivided that a man is not considered a machinist at all. One man may make just a particular part of a machine and may not know anything whatever about another part of the same machine. . . . The machinist has almost become a cipher in the shop. . . . He is simply a laborer.`,
        caption: null,
        mediaType: 'text',
        imageUrl: null,
        imageAlt: null,
        provenanceUrl: null,
      },
      {
        externalKey: 'apush-dbq-gilded-age-doc-3',
        position: 3,
        title: 'Doc 3 — Haymarket Square',
        attribution: `Engraving published in Harper's Weekly, May 15, 1886, depicting the bombing and police response at Haymarket Square, Chicago, during a rally in support of the eight-hour workday.`,
        body: `A dramatic wood engraving of the Haymarket affair. A speaker gestures from a wagon on the left as a bomb explodes in a burst of light amid ranks of helmeted police; the surrounding crowd scatters in panic as gunfire erupts between police and members of the rally. The image framed the eight-hour movement in the public mind as violent anarchism.`,
        caption: `Harper's Weekly, May 15, 1886 (Library of Congress).`,
        mediaType: 'image',
        imageUrl: null,
        imageAlt: `1886 Harper's Weekly engraving of the Haymarket Square bombing in Chicago, showing an explosion amid police ranks and a scattering crowd during an eight-hour-workday rally.`,
        provenanceUrl: 'https://www.loc.gov/',
      },
      {
        externalKey: 'apush-dbq-gilded-age-doc-4',
        position: 4,
        title: 'Doc 4 — Carnegie, “Wealth”',
        attribution: `Andrew Carnegie, "Wealth," published in the North American Review, June 1889.`,
        body: `The price which society pays for the law of competition, like the price it pays for cheap comforts and luxuries, is also great; but the advantages of this law are also greater still, for it is to this law that we owe our wonderful material development, which brings improved conditions in its train. . . . We accept and welcome, therefore, as conditions to which we must accommodate ourselves, great inequality of environment, the concentration of business, industrial and commercial, in the hands of a few, and the law of competition between these, as being not only beneficial, but essential for the future progress of the race.`,
        caption: null,
        mediaType: 'text',
        imageUrl: null,
        imageAlt: null,
        provenanceUrl: null,
      },
      {
        externalKey: 'apush-dbq-gilded-age-doc-5',
        position: 5,
        title: 'Doc 5 — Gompers, “What Does the Working Man Want?”',
        attribution: `Samuel Gompers, president of the American Federation of Labor, "What Does the Working Man Want?" speech delivered in Louisville, Kentucky, 1890.`,
        body: `My friends, we have met here today to celebrate the idea that has prompted thousands of working-people . . . to declare their rights to a normal day's work of eight hours. . . . We want eight hours and nothing less. We have been accused of being selfish, and it has been said that we will want more. . . . We do want more. You will find that a man generally wants more. . . . We live in the latter part of the nineteenth century. . . . We are producing wealth today at a greater rate than ever before, and what we want is a fairer share of it for the men who make it.`,
        caption: null,
        mediaType: 'text',
        imageUrl: null,
        imageAlt: null,
        provenanceUrl: null,
      },
      {
        externalKey: 'apush-dbq-gilded-age-doc-6',
        position: 6,
        title: 'Doc 6 — Pullman Strike',
        attribution: `Photograph taken during the Pullman Strike, 1894, showing the Illinois National Guard and striking workers in front of a railroad building in Chicago.`,
        body: `A photograph of the Pullman Strike. Ranks of Illinois National Guardsmen are drawn up in formation before the imposing Pullman administration building while a large crowd of striking workers and onlookers gathers. President Cleveland ordered federal troops to Chicago over the objection of Illinois Governor John Altgeld; the strike was broken within weeks.`,
        caption: `Photograph, Chicago, 1894 (Library of Congress).`,
        mediaType: 'image',
        imageUrl: null,
        imageAlt: `1894 photograph of the Pullman Strike, showing Illinois National Guard troops formed up before the Pullman administration building as a crowd of strikers looks on.`,
        provenanceUrl: 'https://www.loc.gov/',
      },
      {
        externalKey: 'apush-dbq-gilded-age-doc-7',
        position: 7,
        title: 'Doc 7 — Statement of the Pullman strikers',
        attribution: `Statement of the Pullman strikers to the convention of the American Railway Union, Chicago, June 15, 1894.`,
        body: `Five reductions in wages, in work, and in conditions of employment swept through the shops at Pullman between May and December, 1893. . . . Water which Pullman buys from the city at 8 cents a thousand gallons he retails to us at 500 percent advance. . . . Pullman, both the man and the town, is an ulcer on the body politic. He owns the houses, the schoolhouses, and churches of God in the town he gave his once humble name. . . . And thus the merry war—the dance of skeletons bathed in human tears—goes on; and it will go on, brothers, forever, unless you, the American Railway Union, stop it.`,
        caption: null,
        mediaType: 'text',
        imageUrl: null,
        imageAlt: null,
        provenanceUrl: null,
      },
    ],
  },
  {
    externalKey: 'apush-dbq-progressive-era',
    course: 'apush',
    essayType: 'dbq',
    title: 'The Progressive Era',
    prompt: `Evaluate the extent to which Progressive Era reformers succeeded in bringing about social and political change in the United States in the period from 1890 to 1920.`,
    period: '1890-1920',
    periodNumber: 7,
    reasoningSkill: 'continuity-and-change',
    difficulty: 'exam-ready',
    skillEmphasis: 'evidence',
    defaultTimeMode: 'untimed',
    defaultDurationMinutes: 60,
    provenanceUrl: 'https://www.loc.gov/',
    sources: [
      {
        externalKey: 'apush-dbq-progressive-era-doc-1',
        position: 1,
        title: 'Doc 1 — How the Other Half Lives',
        attribution: `Jacob Riis, How the Other Half Lives: Studies among the Tenements of New York, 1890.`,
        body: `Long ago it was said that "one half of the world does not know how the other half lives." That was true then. It did not know because it did not care. The half that was on top cared little for the struggles, and less for the fate of those who were underneath, so long as it was able to hold them there and keep its own seat. . . . In the tenements all the influences make for evil; because they are the hot-beds of the epidemics that carry death to rich and poor alike; the nurseries of pauperism and crime that fill our jails and police courts. . . . We know now that there is no way out; that the "system" that was the evil offspring of public neglect and private greed has come to stay.`,
        caption: null,
        mediaType: 'text',
        imageUrl: null,
        imageAlt: null,
        provenanceUrl: null,
      },
      {
        externalKey: 'apush-dbq-progressive-era-doc-2',
        position: 2,
        title: 'Doc 2 — The Jungle',
        attribution: `Upton Sinclair, The Jungle, a novel exposing conditions in the Chicago meatpacking industry, 1906.`,
        body: `There was never the least attention paid to what was cut up for sausage; there would come all the way back from Europe old sausage that had been rejected, and that was moldy and white—it would be dosed with borax and glycerine, and dumped into the hoppers, and made over again for home consumption. There would be meat that had tumbled out on the floor, in the dirt and sawdust, where the workers had tramped and spit uncounted billions of consumption germs. . . . There were things that went into the sausage in comparison with which a poisoned rat was a tidbit.`,
        caption: null,
        mediaType: 'text',
        imageUrl: null,
        imageAlt: null,
        provenanceUrl: null,
      },
      {
        externalKey: 'apush-dbq-progressive-era-doc-3',
        position: 3,
        title: 'Doc 3 — Lewis Hine, child labor photographs',
        attribution: `Photographs by Lewis Hine for the National Child Labor Committee: (a) Addie Card, a twelve-year-old spinner in a cotton mill, North Pownal, Vermont, 1910; (b) young boys working at Bibb Mill No. 1, Macon, Georgia, 1909.`,
        body: `Two documentary photographs. (a) A young girl in a worn dress stands barefoot beside towering rows of spinning machines, dwarfed by the industrial equipment she tends. (b) Several small boys in caps climb on and work the spinning frames of a textile mill. Hine's photographs were circulated by the National Child Labor Committee to build public support for state and federal child labor laws.`,
        caption: `Lewis Hine, National Child Labor Committee, 1909–1910.`,
        mediaType: 'image',
        imageUrl: null,
        imageAlt: `Two 1909–1910 photographs of child laborers in Southern textile mills: a barefoot girl beside spinning machines, and young boys working the spinning frames.`,
        provenanceUrl:
          'https://www.loc.gov/pictures/search/?q=lewis+hine+national+child+labor+committee',
      },
      {
        externalKey: 'apush-dbq-progressive-era-doc-4',
        position: 4,
        title: 'Doc 4 — Twenty Years at Hull-House',
        attribution: `Jane Addams, founder of Hull House in Chicago, Twenty Years at Hull-House, 1910.`,
        body: `We early learned to know the children of hard-driven mothers who went out to work all day, sometimes leaving the little things in the casual care of a neighbor, but often locking them into their tenement rooms. . . . The Settlement, then, is an experimental effort to aid in the solution of the social and industrial problems which are engendered by the modern conditions of life in a great city. . . . It must be grounded in a philosophy whose foundation is on the solidarity of the human race.`,
        caption: null,
        mediaType: 'text',
        imageUrl: null,
        imageAlt: null,
        provenanceUrl: null,
      },
      {
        externalKey: 'apush-dbq-progressive-era-doc-5',
        position: 5,
        title: 'Doc 5 — The New Nationalism',
        attribution: `Theodore Roosevelt, "The New Nationalism," speech delivered at Osawatomie, Kansas, August 31, 1910.`,
        body: `The citizens of the United States must effectively control the mighty commercial forces which they have themselves called into being. There can be no effective control of corporations while their political activity remains. To put an end to it will be neither a short nor an easy task, but it can be done. . . . This New Nationalism regards the executive power as the steward of the public welfare. It demands of the judiciary that it shall be interested primarily in human welfare rather than in property.`,
        caption: null,
        mediaType: 'text',
        imageUrl: null,
        imageAlt: null,
        provenanceUrl: null,
      },
      {
        externalKey: 'apush-dbq-progressive-era-doc-6',
        position: 6,
        title: 'Doc 6 — Woman Suffrage Headquarters',
        attribution: `Photograph of the Woman Suffrage Headquarters in Cleveland, Ohio, during the campaign for a state suffrage amendment, 1912.`,
        body: `A storefront serving as a woman suffrage campaign headquarters. A large banner reads: "Woman Suffrage Headquarters. Men of Ohio! Give the women a square deal. Vote for Amendment No. 23 on September 3, 1912," with a smaller sign urging passersby to "Come in and learn why women ought to vote." Suffrage campaigners stand in the doorway. The 1912 Ohio amendment was defeated; Ohio women gained the vote with the Nineteenth Amendment in 1920.`,
        caption: `Photograph, Cleveland, Ohio, 1912.`,
        mediaType: 'image',
        imageUrl: null,
        imageAlt: `1912 photograph of a Cleveland storefront woman-suffrage headquarters with a large banner appealing to the men of Ohio to vote for the suffrage amendment.`,
        provenanceUrl: 'https://www.loc.gov/',
      },
      {
        externalKey: 'apush-dbq-progressive-era-doc-7',
        position: 7,
        title: 'Doc 7 — The Souls of Black Folk',
        attribution: `W. E. B. Du Bois, The Souls of Black Folk, 1903.`,
        body: `The problem of the twentieth century is the problem of the color-line. . . . By every civilized and peaceful method we must strive for the rights which the world accords to men, clinging unwaveringly to those great words which the sons of the Fathers would fain forget: "We hold these truths to be self-evident: That all men are created equal; that they are endowed by their Creator with certain unalienable rights; that among these are life, liberty, and the pursuit of happiness."`,
        caption: null,
        mediaType: 'text',
        imageUrl: null,
        imageAlt: null,
        provenanceUrl: null,
      },
    ],
  },
  {
    externalKey: 'apush-dbq-american-imperialism',
    course: 'apush',
    essayType: 'dbq',
    title: 'American Imperialism',
    prompt: `Evaluate the extent of change in United States foreign policy in the period from 1890 to 1917.`,
    period: '1890-1917',
    periodNumber: 7,
    reasoningSkill: 'continuity-and-change',
    difficulty: 'exam-ready',
    skillEmphasis: 'sourcing-heavy',
    defaultTimeMode: 'untimed',
    defaultDurationMinutes: 60,
    provenanceUrl: 'https://www.loc.gov/',
    sources: [
      {
        externalKey: 'apush-dbq-american-imperialism-doc-1',
        position: 1,
        title: 'Doc 1 — Mahan, The Influence of Sea Power',
        attribution: `Alfred Thayer Mahan, United States Navy captain, The Influence of Sea Power upon History, 1890.`,
        body: `Whether they will or no, Americans must now begin to look outward. The growing production of the country demands it. An increasing volume of public sentiment demands it. . . . Three things are needful: First, protection of the chief harbors by fortifications and coast-defence ships. . . . Secondly, naval force, the arm of offensive power, which alone enables a country to extend its influence outward. Thirdly, no foreign state should henceforth acquire a coaling position within three thousand miles of San Francisco.`,
        caption: null,
        mediaType: 'text',
        imageUrl: null,
        imageAlt: null,
        provenanceUrl: null,
      },
      {
        externalKey: 'apush-dbq-american-imperialism-doc-2',
        position: 2,
        title: 'Doc 2 — Beveridge, “The March of the Flag”',
        attribution: `Albert J. Beveridge, candidate for the United States Senate from Indiana, "The March of the Flag," campaign speech, September 16, 1898.`,
        body: `It is a noble land that God has given us. . . . Shall the American people continue their march toward the commercial supremacy of the world? Shall free institutions broaden their blessed reign as the children of liberty wax in strength, until the empire of our principles is established over the hearts of all mankind? . . . The Opposition tells us that we ought not to govern a people without their consent. I answer, The rule of liberty that all just government derives its authority from the consent of the governed, applies only to those who are capable of self-government.`,
        caption: null,
        mediaType: 'text',
        imageUrl: null,
        imageAlt: null,
        provenanceUrl: null,
      },
      {
        externalKey: 'apush-dbq-american-imperialism-doc-3',
        position: 3,
        title: 'Doc 3 — “Ten Thousand Miles from Tip to Tip”',
        attribution: `"Ten Thousand Miles from Tip to Tip," cartoon published in the Philadelphia Press, 1898, showing an American eagle with wings stretching from Puerto Rico to the Philippines; the smaller map shows the United States in 1798.`,
        body: `A political cartoon celebrating American expansion. A giant bald eagle, dated "1898," spreads its wings across a map so that they reach from Puerto Rico in the east to Manila and the Ladrones (Guam) in the west, superimposed over the continental United States. An inset map shows the far smaller United States of 1798. The cartoon appeared shortly after the United States acquired Puerto Rico, Guam, and the Philippines in the Treaty of Paris ending the Spanish-American War.`,
        caption: `Philadelphia Press, 1898.`,
        mediaType: 'image',
        imageUrl: null,
        imageAlt: `1898 cartoon "Ten Thousand Miles from Tip to Tip," a bald eagle whose wings span from Puerto Rico to the Philippines over a US map, contrasted with a small inset map of the United States in 1798.`,
        provenanceUrl: 'https://www.loc.gov/',
      },
      {
        externalKey: 'apush-dbq-american-imperialism-doc-4',
        position: 4,
        title: 'Doc 4 — Anti-Imperialist League platform',
        attribution: `Platform of the American Anti-Imperialist League, adopted at Chicago, October 17, 1899.`,
        body: `We hold that the policy known as imperialism is hostile to liberty and tends toward militarism, an evil from which it has been our glory to be free. We regret that it has become necessary in the land of Washington and Lincoln to reaffirm that all men, of whatever race or color, are entitled to life, liberty, and the pursuit of happiness. We maintain that governments derive their just powers from the consent of the governed. We insist that the subjugation of any people is "criminal aggression" and open disloyalty to the distinctive principles of our Government.`,
        caption: null,
        mediaType: 'text',
        imageUrl: null,
        imageAlt: null,
        provenanceUrl: null,
      },
      {
        externalKey: 'apush-dbq-american-imperialism-doc-5',
        position: 5,
        title: 'Doc 5 — The Roosevelt Corollary',
        attribution: `Theodore Roosevelt, Annual Message to Congress (the "Roosevelt Corollary" to the Monroe Doctrine), December 6, 1904.`,
        body: `It is not true that the United States feels any land hunger or entertains any projects as regards the other nations of the Western Hemisphere save such as are for their welfare. All that this country desires is to see the neighboring countries stable, orderly, and prosperous. . . . Chronic wrongdoing, or an impotence which results in a general loosening of the ties of civilized society, may in America, as elsewhere, ultimately require intervention by some civilized nation, and in the Western Hemisphere the adherence of the United States to the Monroe Doctrine may force the United States, however reluctantly, in flagrant cases of such wrongdoing or impotence, to the exercise of an international police power.`,
        caption: null,
        mediaType: 'text',
        imageUrl: null,
        imageAlt: null,
        provenanceUrl: null,
      },
      {
        externalKey: 'apush-dbq-american-imperialism-doc-6',
        position: 6,
        title: 'Doc 6 — “The Big Stick in the Caribbean Sea”',
        attribution: `William Allen Rogers, "The Big Stick in the Caribbean Sea," cartoon published in Harper's Magazine, 1904, depicting President Theodore Roosevelt wading through the Caribbean pulling a string of ships.`,
        body: `A political cartoon of the "Big Stick" diplomacy. A towering Theodore Roosevelt, shouldering an enormous club, wades knee-deep through the Caribbean Sea, towing a line of warships in his wake past small island nations. The ships are labeled with the debts and customs-receivership disputes of Caribbean nations; the cartoon refers to Roosevelt's proverb, "Speak softly and carry a big stick."`,
        caption: `Harper's Magazine, 1904 (Library of Congress).`,
        mediaType: 'image',
        imageUrl: null,
        imageAlt: `1904 cartoon "The Big Stick in the Caribbean Sea," showing a giant Theodore Roosevelt carrying a huge club and wading through the Caribbean, towing a string of warships past small island nations.`,
        provenanceUrl: 'https://www.loc.gov/',
      },
      {
        externalKey: 'apush-dbq-american-imperialism-doc-7',
        position: 7,
        title: 'Doc 7 — Wilson’s war message',
        attribution: `Woodrow Wilson, address to a joint session of Congress requesting a declaration of war against Germany, April 2, 1917.`,
        body: `We have no selfish ends to serve. We desire no conquest, no dominion. We seek no indemnities for ourselves, no material compensation for the sacrifices we shall freely make. We are but one of the champions of the rights of mankind. . . . The world must be made safe for democracy. Its peace must be planted upon the tested foundations of political liberty. . . . It is a fearful thing to lead this great peaceful people into war, into the most terrible and disastrous of all wars, civilization itself seeming to be in the balance. But the right is more precious than peace.`,
        caption: null,
        mediaType: 'text',
        imageUrl: null,
        imageAlt: null,
        provenanceUrl: null,
      },
    ],
  },
  {
    externalKey: 'apush-dbq-1920s-tradition-modernity',
    course: 'apush',
    essayType: 'dbq',
    title: 'The 1920s: Tradition and Modernity',
    prompt: `Evaluate the extent to which conflict between traditional and modern values shaped American society in the 1920s.`,
    period: '1920-1929',
    periodNumber: 7,
    reasoningSkill: 'causation',
    difficulty: 'exam-ready',
    skillEmphasis: 'complexity-heavy',
    defaultTimeMode: 'untimed',
    defaultDurationMinutes: 60,
    provenanceUrl: 'https://www.loc.gov/',
    sources: [
      {
        externalKey: 'apush-dbq-1920s-tradition-modernity-doc-1',
        position: 1,
        title: 'Doc 1 — “A Flapper’s Appeal to Parents”',
        attribution: `Ellen Welles Page, "A Flapper's Appeal to Parents," published in Outlook magazine, December 6, 1922.`,
        body: `I am a flapper. I wear bobbed hair, the badge of flapperhood. . . . I powder my nose. I wear fringed skirts and bright-colored sweaters, and scarfs, and waists with Peter Pan collars, and low-heeled "finale hopper" shoes. I adore to dance. I spend a large amount of time in automobiles. I attend hops, and proms, and ball-games, and crew races, and other affairs at men's colleges. . . . Most of us, under the present system of modern education, are further advanced and more thoroughly developed mentally, physically, and vocationally than were our parents at our age. . . . We are the Younger Generation. The war tore away our spiritual foundations and challenged our faith.`,
        caption: null,
        mediaType: 'text',
        imageUrl: null,
        imageAlt: null,
        provenanceUrl: null,
      },
      {
        externalKey: 'apush-dbq-1920s-tradition-modernity-doc-2',
        position: 2,
        title: 'Doc 2 — Saturday Evening Post cover',
        attribution: `Cover of the Saturday Evening Post, February 4, 1922.`,
        body: `A magazine cover illustration of a fashionable young woman — the "New Woman" of the 1920s — with bobbed hair, rouged cheeks and lips, and a modern sleeveless dress, gazing out at the reader. Mass-circulation magazines like the Saturday Evening Post carried images of bobbed hair, cosmetics, and modern fashion into millions of American homes each week.`,
        caption: `The Saturday Evening Post, February 4, 1922.`,
        mediaType: 'image',
        imageUrl: null,
        imageAlt: `Saturday Evening Post cover of February 4, 1922, illustrating a fashionable young "New Woman" with bobbed hair and cosmetics.`,
        provenanceUrl: 'https://www.loc.gov/',
      },
      {
        externalKey: 'apush-dbq-1920s-tradition-modernity-doc-3',
        position: 3,
        title: 'Doc 3 — “The Klan’s Fight for Americanism”',
        attribution: `Hiram Wesley Evans, Imperial Wizard of the Ku Klux Klan, "The Klan's Fight for Americanism," published in the North American Review, March 1926.`,
        body: `The Klan, therefore, has now come to speak for the great mass of Americans of the old pioneer stock. . . . These are, in the first place, a blend of various peoples of the so-called Nordic race. . . . Nordic Americans for the last generation have found themselves increasingly uncomfortable, and finally deeply distressed. . . . One by one all our traditional moral standards went by the boards, or were so disregarded that they ceased to be binding. The sacredness of our Sabbath, of our homes, of chastity, and finally even of our right to teach our own children in our own schools fundamental facts and truths were torn away from us.`,
        caption: null,
        mediaType: 'text',
        imageUrl: null,
        imageAlt: null,
        provenanceUrl: null,
      },
      {
        externalKey: 'apush-dbq-1920s-tradition-modernity-doc-4',
        position: 4,
        title: 'Doc 4 — Anti-Evolution League, Scopes trial',
        attribution: `Photograph of T. T. Martin's Anti-Evolution League book stand, Dayton, Tennessee, during the trial of John Scopes for teaching evolution in a public school, July 1925.`,
        body: `A photograph taken on a street in Dayton, Tennessee, during the Scopes "Monkey" Trial. A crowd of men in shirtsleeves and straw hats gathers around an open-air book stand under banners reading "T. T. MARTIN, HEADQUARTERS — ANTI-EVOLUTION LEAGUE" and "THE CONFLICT — HELL & THE HIGH SCHOOL." Signs advertise the League's books. The Scopes trial drew national press coverage and radio broadcast, framing the conflict between fundamentalism and modern science.`,
        caption: `Photograph, Dayton, Tennessee, July 1925 (Smithsonian Institution).`,
        mediaType: 'image',
        imageUrl: null,
        imageAlt: `1925 photograph of T. T. Martin's Anti-Evolution League book stand at the Scopes trial in Dayton, Tennessee, with banners reading "Hell and the High School" and a crowd of onlookers.`,
        provenanceUrl: 'https://www.loc.gov/',
      },
      {
        externalKey: 'apush-dbq-1920s-tradition-modernity-doc-5',
        position: 5,
        title: 'Doc 5 — Bryan’s closing argument',
        attribution: `William Jennings Bryan, from the closing argument prepared for the Scopes trial, published shortly after his death, 1925.`,
        body: `Science is a magnificent material force, but it is not a teacher of morals. It can perfect machinery, but it adds no moral restraints to protect society from the misuse of the machine. . . . If civilization is to be saved from the wreckage threatened by intelligence not consecrated by love, it must be saved by the moral code of the meek and lowly Nazarene. His teachings, and His teachings alone, can solve the problems that vex the heart and perplex the world.`,
        caption: null,
        mediaType: 'text',
        imageUrl: null,
        imageAlt: null,
        provenanceUrl: null,
      },
      {
        externalKey: 'apush-dbq-1920s-tradition-modernity-doc-6',
        position: 6,
        title: 'Doc 6 — “The Negro Artist and the Racial Mountain”',
        attribution: `Langston Hughes, "The Negro Artist and the Racial Mountain," published in The Nation, June 23, 1926.`,
        body: `We younger Negro artists who create now intend to express our individual dark-skinned selves without fear or shame. If white people are pleased we are glad. If they are not, it doesn't matter. We know we are beautiful. And ugly too. The tom-tom cries and the tom-tom laughs. If colored people are pleased we are glad. If they are not, their displeasure doesn't matter either. We build our temples for tomorrow, strong as we know how, and we stand on top of the mountain, free within ourselves.`,
        caption: null,
        mediaType: 'text',
        imageUrl: null,
        imageAlt: null,
        provenanceUrl: null,
      },
      {
        externalKey: 'apush-dbq-1920s-tradition-modernity-doc-7',
        position: 7,
        title: 'Doc 7 — “Shut the Door”',
        attribution: `Senator Ellison DuRant Smith of South Carolina, "Shut the Door," speech in the United States Senate in support of the Immigration Act of 1924, April 9, 1924.`,
        body: `I think we now have sufficient population in our country for us to shut the door and to breed up a pure, unadulterated American citizenship. . . . Thank God we have in America perhaps the largest percentage of any country in the world of the pure, unadulterated Anglo-Saxon stock. . . . It is for the preservation of that splendid stock that has characterized us that I would make this not an asylum for the oppressed of all countries, but a country to assimilate and perfect that splendid type of manhood that has made America the foremost Nation in her progress and in her power.`,
        caption: null,
        mediaType: 'text',
        imageUrl: null,
        imageAlt: null,
        provenanceUrl: null,
      },
    ],
  },
] as const;
