export const AP_HISTORY_LIBRARY_ENTRIES = [
  {
    externalKey: 'apush-dbq-new-deal-federal-power',
    course: 'apush',
    essayType: 'dbq',
    title: 'New Deal and Federal Power DBQ',
    prompt:
      'Evaluate the extent to which the New Deal changed the role of the federal government in the United States.',
    period: '1932-1980',
    periodNumber: 7,
    reasoningSkill: 'causation',
    difficulty: 'exam-ready',
    skillEmphasis: 'evidence',
    defaultTimeMode: 'untimed',
    defaultDurationMinutes: 60,
    provenanceUrl: 'https://apcentral.collegeboard.org/',
    sources: [
      {
        externalKey: 'apush-dbq-new-deal-federal-power-doc-1',
        position: 1,
        title: 'Document 1',
        attribution: 'Franklin D. Roosevelt, first inaugural address, 1933',
        body:
          'This Nation asks for action, and action now. Our greatest primary task is to put people to work.',
        caption: 'Roosevelt outlines federal response to economic crisis.',
        mediaType: 'text',
        imageUrl: null,
        imageAlt: null,
        provenanceUrl: 'https://apcentral.collegeboard.org/',
      },
      {
        externalKey: 'apush-dbq-new-deal-federal-power-doc-2',
        position: 2,
        title: 'Document 2',
        attribution: 'Social Security Act summary, 1935',
        body:
          'The Act created old-age benefits and unemployment insurance funded through payroll taxes.',
        caption: 'Federal welfare-state expansion during the New Deal.',
        mediaType: 'text',
        imageUrl: null,
        imageAlt: null,
        provenanceUrl: 'https://apcentral.collegeboard.org/',
      },
    ],
  },
  {
    externalKey: 'apush-leq-market-revolution',
    course: 'apush',
    essayType: 'leq',
    title: 'Market Revolution LEQ',
    prompt:
      'Evaluate the extent to which the Market Revolution transformed United States society in the period from 1815 to 1848.',
    period: '1815-1848',
    periodNumber: 4,
    reasoningSkill: 'causation',
    difficulty: 'intro',
    skillEmphasis: 'outside-evidence',
    defaultTimeMode: 'untimed',
    defaultDurationMinutes: 40,
    provenanceUrl: 'https://apcentral.collegeboard.org/',
    sources: [],
  },
] as const;
