#!/usr/bin/env python3
# Regenerate the AP History Essay library data from the canonical xlsx.
#
# Source of truth: docs/content/yawp_apush_library_v1.xlsx
# Output target:   services/web-app/app/routes/app.assignment-types.$id/library-data.ts
#
# The xlsx has two tabs (PROMPTS and SOURCES). This script reads them and
# emits the SAMPLE_PROMPTS array, the SOURCES_DBQ_* consts, and the
# SOURCES_BY_PROMPT_ID map into a block of TypeScript bracketed by
# // <library:begin auto-generated> and // <library:end>.
#
# Usage:
#   pip install openpyxl
#   python3 scripts/ingest-library.py
#
# After running, review the diff and commit. Anything outside the
# auto-generated block (types, helpers, MOCK_TEACHER_CLASSES, etc.) is
# preserved.

from collections import Counter, defaultdict
from pathlib import Path
import re
import sys

try:
    import openpyxl
except ImportError:
    sys.exit("Missing dependency: pip install openpyxl")

REPO = Path(__file__).resolve().parent.parent
XLSX = REPO / 'docs' / 'content' / 'yawp_apush_library_v1.xlsx'
TS_FILE = (
    REPO
    / 'services'
    / 'web-app'
    / 'app'
    / 'routes'
    / 'app.assignment-types.$id'
    / 'library-data.ts'
)

BEGIN_MARKER = '// <library:begin auto-generated by scripts/ingest-library.py>'
END_MARKER = '// <library:end>'


def ts_template(s: str | None) -> str:
    """Render a string as a TypeScript template literal."""
    if s is None:
        return 'null'
    escaped = (
        str(s)
        .replace('\\', '\\\\')
        .replace('`', '\\`')
        .replace('${', '\\${')
    )
    return '`' + escaped + '`'


def ts_single(s: str | None) -> str:
    """Render a short string as a single-quoted TS string."""
    if s is None:
        return 'null'
    escaped = str(s).replace('\\', '\\\\').replace("'", "\\'")
    return "'" + escaped + "'"


def safe_const_name(prompt_id: str) -> str:
    return 'SOURCES_' + re.sub(r'[^A-Za-z0-9]', '_', prompt_id)


def main() -> int:
    if not XLSX.exists():
        sys.exit(f"Missing xlsx at {XLSX}")

    wb = openpyxl.load_workbook(XLSX, data_only=True)

    # ---- PROMPTS ----
    ws = wb['PROMPTS']
    headers = [c.value for c in ws[1]]
    prompts = []
    for row in ws.iter_rows(min_row=2, values_only=True):
        if all(v is None for v in row):
            continue
        prompts.append(dict(zip(headers, row)))

    # ---- SOURCES ----
    ws = wb['SOURCES']
    headers = [c.value for c in ws[1]]
    sources = []
    for row in ws.iter_rows(min_row=2, values_only=True):
        if all(v is None for v in row):
            continue
        sources.append(dict(zip(headers, row)))

    src_count = Counter(s['prompt_id'] for s in sources)
    by_prompt: dict[str, list] = defaultdict(list)
    for s in sources:
        by_prompt[s['prompt_id']].append(s)
    for pid in by_prompt:
        by_prompt[pid].sort(key=lambda s: s['order'])

    # ---- Emit TS ----
    out: list[str] = []
    out.append(BEGIN_MARKER)
    out.append('// Do not edit by hand. Run `python3 scripts/ingest-library.py`')
    out.append('// after editing docs/content/yawp_apush_library_v1.xlsx.')
    out.append('')
    out.append('export const SAMPLE_PROMPTS: LibraryPrompt[] = [')
    for p in prompts:
        is_dbq = p['type'] == 'DBQ'
        sc = src_count.get(p['id'], 0) if is_dbq else 'null'
        emph = [
            e.strip()
            for e in (p['skill_emphasis'] or '').split(',')
            if e.strip()
        ]
        out.append('  {')
        out.append(f"    id: {ts_single(p['id'])},")
        out.append(f"    type: {ts_single(p['type'])},")
        out.append(f"    period: {ts_single(p['period'])},")
        out.append(f"    prompt: {ts_template(p['prompt'])},")
        out.append(f"    era: {ts_single(p['era'])},")
        out.append(f"    sourceCount: {sc},")
        out.append(f"    reasoning: {ts_single(p['reasoning'])},")
        emph_ts = '[' + ', '.join(ts_single(e) for e in emph) + ']'
        out.append(f"    skillEmphasis: {emph_ts},")
        out.append(f"    difficulty: {ts_single(p['difficulty'])},")
        out.append('  },')
    out.append('];')
    out.append('')

    for pid in sorted(by_prompt.keys()):
        out.append(f'const {safe_const_name(pid)}: SourceCard[] = [')
        for s in by_prompt[pid]:
            out.append('  {')
            out.append(f"    id: 'src-{s['order']}',")
            out.append(f"    title: {ts_template(s['title'])},")
            out.append(f"    attribution: {ts_template(s['attribution'])},")
            out.append(f"    body: {ts_template(s['body'])},")
            out.append('  },')
        out.append('];')
        out.append('')

    out.append(
        'export const SOURCES_BY_PROMPT_ID: Record<string, SourceCard[]> = {'
    )
    for pid in sorted(by_prompt.keys()):
        out.append(f"  '{pid}': {safe_const_name(pid)},")
    out.append('};')
    out.append('')
    out.append(END_MARKER)

    generated = '\n'.join(out)

    # ---- Splice into library-data.ts ----
    src = TS_FILE.read_text()
    if BEGIN_MARKER not in src or END_MARKER not in src:
        sys.exit(
            f"Markers not found in {TS_FILE}. Add this between the markers:\n\n"
            f"{BEGIN_MARKER}\n…\n{END_MARKER}"
        )

    pattern = re.compile(
        re.escape(BEGIN_MARKER) + r'.*?' + re.escape(END_MARKER),
        re.DOTALL,
    )
    new_src = pattern.sub(generated, src)
    TS_FILE.write_text(new_src)

    print(
        f"Ingested {len(prompts)} prompts "
        f"({sum(1 for p in prompts if p['type']=='DBQ')} DBQ, "
        f"{sum(1 for p in prompts if p['type']=='LEQ')} LEQ) "
        f"and {len(sources)} sources into {TS_FILE.relative_to(REPO)}."
    )
    return 0


if __name__ == '__main__':
    sys.exit(main())
