name: 🚁 Preview

on:
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_REGION: atl
  FLY_ORG: yawp

jobs:
  lint:
    name: ⬣ ESLint
    runs-on: ubuntu-22.04
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: 📥 Download deps
        uses: oven-sh/setup-bun@v1

      - name: 🔬 Lint
        run: bun i && bun lint

  typecheck:
    name: ʦ TypeScript
    runs-on: ubuntu-22.04
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: 📥 Download deps
        uses: oven-sh/setup-bun@v1

      - name: 🔎 Type check
        run: bun i && bun typecheck

  vitest:
    name: ⚡ Vitest
    runs-on: ubuntu-22.04
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: 📥 Download deps
        uses: oven-sh/setup-bun@v1

      - name: 🏄 Copy test env vars
        run: cp .env.example .env

      - name: ⚡ Run vitest
        run: bun i && bun test -- --coverage

  deploy:
    name: 🚀 Deploy
    needs: [lint, typecheck, vitest]
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.deploy.outputs.url }}
    concurrency:
      group: pr-${{ github.event.number }}

    environment:
      name: review
      url: ${{ steps.deploy.outputs.url }}

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: 🚚 Move Dockerfile
        run: |
          mv ./other/Dockerfile ./Dockerfile
          mv ./other/.dockerignore ./.dockerignore

      - name: 🚀 Deploy Preview
        id: deploy
        uses: JoeyRichter/fly-pr-review-apps@main
        with:
          name: yawp-school-${{ github.event.number }}
          config: fly.preview.toml
          build_secrets: |
            AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: 🎈 Setup Fly
        uses: superfly/flyctl-actions/setup-flyctl@v1.4

      - name: ✨ Finalize
        run: |
          flyctl secrets set ENV=staging ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }} OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} OPENAI_ORG=${{ secrets.OPENAI_ORG }} ALLOW_INDEXING=false SESSION_SECRET=$(openssl rand -hex 32) INTERNAL_COMMAND_TOKEN=${{ secrets.PREVIEW_INTERNAL_COMMAND_TOKEN }} HONEYPOT_SECRET=$(openssl rand -hex 32) --app ${{ steps.deploy.outputs.name }}
          flyctl consul attach --app ${{ steps.deploy.outputs.name }}

      - name: 🌱 Seed Preview
        run: |
          sleep 10
          curl '${{ steps.deploy.outputs.url }}/api/seed?mode=preview&token=${{ secrets.PREVIEW_INTERNAL_COMMAND_TOKEN }}'
